### ISSUE TITLE
dbcsr_api_c.F: use build system for conditional compilation

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#10]
Currently there is a `#ifdef __C_INTERFACE` to disable the complete module when building without C interface support. This is actually a job for the build system.

**Comment by alazzaro** [comment]
I have changed this part. Now the file is compiled only when CINT=1 is set. I agree that we should make it automatically whenever the compiler supports F2008TS...

**Comment by dev-zero** [comment]
this is solved in both build systems, then
