### ISSUE TITLE
dbcsr_api module

### ISSUE THREAD

**Issue by pseewald** [cp2k/dbcsr#109]
We have a dbcsr_api module that contains all dbcsr types and methods. This allows other codes to use DBCSR with a single .mod file. However do we need to write wrappers for everything? Does it not suffice to make symbols from other modules public in dbcsr_api, i.e. something like:

``` fortran
use dbcsr_types, only: dbcsr_type

public :: dbcsr_type
```

Even if we need to write wrappers, every method in dbcsr_api.F should be an exact copy of a dbcsr method, and dbcsr_api.F should not change methods or add new functionality. Right now we have the problem that it is difficult to move linear algebra methods from CP2K to DBCSR since these are based on dbcsr_api, which should not be used in DBCSR internally.

My suggestion is to make clean up dbcsr_api and make it as thin as possible, however I'm not sure whether we actually need wrappers or not.

**Comment by alazzaro** [comment]
The main reason is to have PRIVATE for internal functionalities, therefore the API is a restricted version of all DBCSR functionalities. As far as I know, the API doesn't introduce any new stuff (please correct me).
Importing stuff from CP2K and put inside DBCSR should be possible. However, my proposal is to add a LA directory where you can use all imported modules from CP2K and still continue to use dbcsr_api (like tensors directory). The forbidden part is to use dbcsr_api in the existing internal DBCSR modules, which would be very confusing...

**Comment by alazzaro** [comment]
Forget to say, the LA directory should have its own API and unittest (again, like the tensors case)

**Comment by pseewald** [comment]
Yes but internal functionality can be made private by not making them public in dbcsr_api, so I'm still wondering why we need wrappers.

**Comment by alazzaro** [comment]
Sorry, I don't understand how you can make them private...
If you have dbcsr_type, for instance, and make it public to external, then people can access internal values, right? Let's, they can access the number of blocks (nblks). So you make internal available for external... 
Could you make an example?

**Comment by pseewald** [comment]
Thank you for the explanation, I do understand now why we wrap types. We just need to make sure that dbcsr_api wrappers are exact replicates of the underlying methods, right now the api routines are sometimes different from the underlying methods i.e. `dbcsr_create_template`, `dbcsr_get_data_p` or `dbcsr_mp_new`.

**Comment by alazzaro** [comment]
That's true... Actually, we have to wrap everything we need with an exact replica, I agree. Let's keep open this issue...

**Comment by dev-zero** [comment]
> Sorry, I don't understand how you can make them private...
> If you have dbcsr_type, for instance, and make it public to external, then people can access internal values, right? Let's, they can access the number of blocks (nblks). So you make internal available for external...

But isn't that a consequence of our semi-OO design? If we would have proper class methods then those could access private types.

**Comment by alazzaro** [comment]
@dev-zero Yes, true, we have to improve the interface, however that is a lot of work on the CP2K side too, so I would consider a very limited number of changes for the time being...

**Comment by dev-zero** [comment]
@dithillobothrium fyi

**Comment by dithillobothrium** [comment]
> As far as I know, the API doesn't introduce any new stuff 

@alazzaro , There are new types which redefine dbcsr_type, dbcsr_p_type, _distribution... 

>my proposal is to add a LA directory where you can use all imported modules from CP2K and still continue to use dbcsr_api 

Ok, if we can use dbcsr_api in internal LA directory, then it is easier to port. I moved Arnoldi API with iterate_matrix.F to LA/. 

But I don't think we need to use modules from CP2K (if I understood correctly). If we use them then they should be moved to DBCSR .

**Comment by alazzaro** [comment]
> > As far as I know, the API doesn't introduce any new stuff
> 
> @alazzaro , There are new types which redefine dbcsr_type, dbcsr_p_type, _distribution...

Again, this is no new stuff... it is a redefinition, which is more restricted (as it is supposed to be for an API). I know, the API can be improved and you are free to propose changes, but keep in mind that any change requires a change in CP2K...
Historically, there were two APIs, which were merged by Ole (see https://github.com/cp2k/dbcsr/commit/c319cb17fa7228b31f66874e3f875bf3171ed98f ).


> 
> > my proposal is to add a LA directory where you can use all imported modules from CP2K and still continue to use dbcsr_api
> 
> Ok, if we can use dbcsr_api in internal LA directory, then it is easier to port. I moved Arnoldi API with iterate_matrix.F to LA/.
> 
> But I don't think we need to use modules from CP2K (if I understood correctly). If we use them then they should be moved to DBCSR .

That's correct, DBCSR was part of CP2K and all the infrastructure were imported. Check if something is missing, we can import it if needed (however we have to do a clean-up of the existing modules, a lot of things are CP2K-specific)

**Comment by dithillobothrium** [comment]
#181
