### ISSUE TITLE
Two tests are failing when -DUSE_CUBLAS=ON

### ISSUE THREAD

**Issue by antoscha** [cp2k/dbcsr#117]
```
The following tests FAILED:
          9 - dbcsr_unittest2 (Failed)
         10 - dbcsr_tensor_unittest (Failed)
```

Commands to reproduce:
```
cmake ..                            \
        -DUSE_CUDA=ON               \
        -DWITH_GPU=K40              \
        -DUSE_CUBLAS=ON
make
make test
```
CUDA 10.0.130, Kepler architecture.
[LastTest.log](https://github.com/cp2k/dbcsr/files/2653475/LastTest.log)

**Comment by alazzaro** [comment]
Could you run the same test without CUBLAS and see if they pass? CUBLAS is still experimental in DBCSR...

**Comment by antoscha** [comment]
Yes, they do. I test features gradually.

**Comment by dev-zero** [comment]
possibly related to #118

**Comment by dev-zero** [comment]
can reproduce with K20X (@alazzaro on our tcgpu1)

**Comment by dev-zero** [comment]
as discussed on Slack, this fixes the test failures with `dbcsr_tensor_unittest` unittest for me, but not the `dbcsr_unittest2`:
```
 test_name large_blocks_1
 The solution is suspicious !
 residual  0.27950E+04, a_norm  0.21440E+03, b_norm  0.21250E+03
 c_norm_in  0.21561E+03, c_norm_out  0.29755E+05, c_norm_dbcsr  0.29755E+05
 Checking the norm of the difference against reference GEMM 
 -- ||C_dbcsr-C_dense||_oo/((||A||_oo+||B||_oo+||C||_oo).N.eps)= 0.78365E+14
 **********************************************************************
  -- TESTING dbcsr_multiply (N, T,            3 , N, N, N) ... FAILED !
 **********************************************************************
 ABORT in /data/tiziano/dbcsr/tests/dbcsr_test_multiply.F:539 Test failed
```

**Comment by antoscha** [comment]
Confirm that https://github.com/cp2k/dbcsr/commit/d97f28787a62e99c02aec38295bc8d88ea6a40e1 fixes `dbcsr_tensor_unittest`. Thank you, @alazzaro!

**Comment by alazzaro** [comment]
@antoscha Could you check with my latest commit? Unfortunately, I don't a system where I can reproduce the problem...

**Comment by antoscha** [comment]
@alazzaro, dbcsr_unittest2 still fails.

**Comment by antoscha** [comment]
The issue with dbcsr_unittest2 seems to be closely related to the number of MPI-ranks used. At my 4-core PC this test passes flawlessly when np < 4, and fails when np = 4. I'm not sure if it's OOM. A dirty hack to make this test passing may be in stating `-DTEST_MPI_RANKS=2` instead of `auto` by default.

**Comment by alazzaro** [comment]
I think I found the reason of the bug. Actually, there were two bugs:
1) a bug when using a high number of ranks (as you noticed). this was not related to cublas
2) a bug specific for cublas (the sync after every call was missing)

@antoscha Could you test my fix?

**Comment by antoscha** [comment]
@alazzaro Now works well, thank you! Should I close the issue?

**Comment by alazzaro** [comment]
> @alazzaro Now works well, thank you! Should I close the issue?

yes, please. We will make a new release. Thanks for finding this bug. Hopefully soon (~1 month) we will have a CI for testing the CUDA implementation...
