### ISSUE TITLE
Building DBCSR with CUBLAS and gfortran-4.8.5 fails

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#118]
**Describe the bug**

```
[  3%] Building Fortran object src/CMakeFiles/dbcsr.dir/data/dbcsr_data_methods.F.o
/data/tiziano/dbcsr/build/src/mm/dbcsr_acc_operations.F:174.47:

                                         C_LOC(param_stack_host(1, 1)), &
                                               1
Error: Assumed-shape array 'param_stack_host' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
/data/tiziano/dbcsr/build/src/mm/dbcsr_acc_operations.F:187.50:

                                            C_LOC(param_stack_host(1, 1)), &
                                                  1
Error: Assumed-shape array 'param_stack_host' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
make[2]: *** [src/CMakeFiles/dbcsr.dir/mm/dbcsr_acc_operations.F.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/dbcsr.dir/all] Error 2
make: *** [all] Error 2
```

**To Reproduce**
1. Built with the command: `PATH="/usr/local/cuda/bin:$PATH" cmake3 .. -DUSE_CUDA=ON -DWITH_GPU=K40 -DUSE_CUBLAS=ON && make` on an up-to-date Centos 7 (therefore gfortran 4.8.5) with CUDA SDK 10
2. See error

Btw, using the hack to get the address of the first element is bad since the array is not guaranteed to be contiguous in Fortran.

**Comment by alazzaro** [comment]
Well, for that we have to move the loop (which is now in the C function) to the Fortran side

**Comment by dithillobothrium** [comment]
Is there another way to pass an array may be? I think these arrays are always contiguous.

**Comment by alazzaro** [comment]
Well, the way would be to copy the arrays in a new one or (better) to use the CONTIGUOUS keyword. Anyway, now the problem is fixed by making an external loop in Fortran. The good point is that we check the transposity for every iteration, so we code is even better :)
