### ISSUE TITLE
libcusmm_unittest_transpose fails with K40

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#123]
**Describe the bug**
```
[...]
13/14 Test #13: libcusmm_unittest_transpose ...........................***Failed    6.60 sec
      Start 14: libcusmm_timer_multiply
14/14 Test #14: libcusmm_timer_multiply ...............................   Passed   29.08 sec

93% tests passed, 1 tests failed out of 14

Total Test time (real) = 193.35 sec

The following tests FAILED:
     13 - libcusmm_unittest_transpose (Failed)
Errors while running CTest
make: *** [test] Error 8
```

**To Reproduce**
1. Built with the command: `PATH="/usr/lib64/openmpi3/bin:/usr/local/cuda/bin:$PATH" cmake3 .. -DUSE_CUDA=ON -DWITH_GPU=K40 -DUSE_CUBLAS=ON` on with two Nvidia GK110BGL (K40c)
2. Run like this: `make test`
3. On the architecture/host/platform: `up-to-date Centos 7`
4. See [LastTest.log](https://github.com/cp2k/dbcsr/files/2656700/LastTest.log)

**Comment by shoshijak** [comment]
Hi, looking at the log you attached: 

```
13/14 Test: libcusmm_unittest_transpose
Command: "/usr/lib64/openmpi3/bin/mpiexec" "-n" "6" "./libcusmm_unittest_transpose"
Directory: /data/tiziano/dbcsr/build/tests
"libcusmm_unittest_transpose" start time: Dec 07 10:43 CET
Output:
----------------------------------------------------------
# Libcusmm has 19 blocksizes for transposition
# Libcusmm has 19 blocksizes for transposition
# Libcusmm has 19 blocksizes for transposition
# Libcusmm has 19 blocksizes for transposition
# Libcusmm has 19 blocksizes for transposition
# Libcusmm has 19 blocksizes for transposition
OK 32 x 32
OK 32 x 32
OK 32 x 32
OK 32 x 32
OK 32 x 32
OK 32 x 32
OK 29 x 29
OK 29 x 29

... only OKs, abridged for conciseness ... 

OK 6 x 6
OK 6 x 6
OK 5 x 5
OK 5 x 5
# Done, found 622573 transpose errors.
```

All transposition are reported `OK`, I don't know why the test reports `622573` transpose errors on only `19 blocksizes * 6 MPI ranks = 114 transpositions`. 

Let me see if I can reproduce this ...

**Comment by shoshijak** [comment]
I don't have access to any K40s unfortunately and cannot seem to reproduce these test results. 
@dev-zero have you ever observed this on a K20, K80 or P100?

**Comment by alazzaro** [comment]
I think this is another evidence of the OOM when using CUBLAS (such as in #117 )

. Indeed, there are 6 MPI ranks, each one is declaring a cublas context. So I have two questions for @dev-zero :
1) do you get the error when cublas is off?
2) have you tried to reduce the number of ranks to 1?

If my guess is correct, then we have to reduce the number of ranks for this test to 1 (these tests are not using MPI anyway).

**Comment by shoshijak** [comment]
I second @alazzaro 's last sentence: all libcusmm tests are on-node anyway, we should run them on just 1 rank

**Comment by dev-zero** [comment]
Ok, I changed the cmake test runner for libcusmm to not run the libcusmm tests through MPI.
About the issue observed here: my guess is that it's a spurious error (since I can't reproduce it anymore) due to a missing initialization, fixed by the referenced commit.
For the curious ones: The C++ compilers do not initialize integers to 0, see: https://godbolt.org/z/g6OCcn

**Comment by shoshijak** [comment]
Shall we close the issue, then?
