### ISSUE TITLE
How to initialize matrix with limited matrix?

### ISSUE THREAD

**Issue by SYFT** [cp2k/dbcsr#125]
Can we initialize matrix from CSR/CSC format while don't have enough memory store the whole array of  block matrix?

**Comment by alazzaro** [comment]
Could you elaborate a bit more what you would like to achieve?
DBCSR is distributed, so you can distribute the data over nodes.

**Comment by SYFT** [comment]
It seems that we can only use dbcsr_put_block to initialize each block matrix while we should pass data as array. But what if we don't have enough memory to store the whole array (because it has too much zeros)? Can we initialize each block matrix with CSR/CSC format?

**Comment by SYFT** [comment]
Thanks. I confused the concept of the "block".
