### ISSUE TITLE
Remove INTENT(OUT)

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#130]

**Comment by alazzaro** [comment]
Yes, this is true and I understand all concerns. Actually, in the past I have problems only with POINTERS marked INTENT(OUT)...

**Comment by dev-zero** [comment]
can you elaborate?

**Comment by alazzaro** [comment]
It was a bug in the compiler (Intel), the INTENT(OUT) for a POINTER was giving an error at the call of the function (the problem was that the pointer was undefined and the compiler was ignoring the INTENT). Currently, a trivial grep gives me 4 calls for such a case:

```
> grep -R "INTENT(OUT)" * | grep POINTER
dist/dbcsr_dist_operations.F:      INTEGER, DIMENSION(:), INTENT(OUT), POINTER        :: bin_dist
mm/dbcsr_mm_cannon.F:      TYPE(dbcsr_2d_array_type), INTENT(OUT), POINTER    :: m2s
mm/dbcsr_mm_3d.F:      INTEGER, DIMENSION(:, :, :), INTENT(OUT), POINTER  :: refs_size_layers3D, refs_displ_layers3D
ops/dbcsr_csr_conversions.F:      INTEGER, DIMENSION(:), INTENT(OUT), POINTER        :: dbcsr_index, csr_index
```
Therefore it is not that common...

We can keep the INTENT, so we can close this issue.
