### ISSUE TITLE
DBCSR unittests don't use the libcusmm backend much

### ISSUE THREAD

**Issue by shoshijak** [cp2k/dbcsr#131]
The DBCSR unit tests provided (`tests/dbcsr_unittest1.F` and `tests/dbcsr_unittest2.F`) do not make much use of the `libcusmm` CUDA backend, as shown in these excerpts from the tests' output (`ACC` column almost always = 0): 

**dbcsr_unittest_1**
```
 -------------------------------------------------------------------------------
 -                                                                             -
 -                                DBCSR STATISTICS                             -
 -                                                                             -
 -------------------------------------------------------------------------------
 COUNTER                                    TOTAL       BLAS       SMM       ACC
 flops     1 x     2 x     1                   64     100.0%      0.0%      0.0%
 flops     2 x     3 x     3                  972     100.0%      0.0%      0.0%
 flops     2 x     3 x     2                 1056     100.0%      0.0%      0.0%
 flops     2 x     2 x     3                 1152     100.0%      0.0%      0.0%
 flops     2 x     2 x     1                 6240     100.0%      0.0%      0.0%
 flops     1 x     2 x     2                11352     100.0%      0.0%      0.0%
 flops     4 x     4 x     4               257536      75.5%      0.0%     24.5%
 flops     2 x     2 x     2            256845504     100.0%      0.0%      0.0%
 flops inhomo. stacks                           0       0.0%      0.0%      0.0%
 flops total                       257.123876E+06     100.0%      0.0%      0.0%
 flops max/rank                     70.539512E+06     100.0%      0.0%      0.0%
 matmuls inhomo. stacks                         0       0.0%      0.0%      0.0%
 matmuls total                           16057190     100.0%      0.0%      0.0%
 number of processed stacks                 46139      99.1%      0.0%      0.9%
 average stack size                                   351.3       0.0       1.2
```

**dbcsr_unittest_2**
```
 -------------------------------------------------------------------------------
 -                                                                             -
 -                                DBCSR STATISTICS                             -
 -                                                                             -
 -------------------------------------------------------------------------------
 COUNTER                                    TOTAL       BLAS       SMM       ACC
 flops   100 x    10 x    10             65740000     100.0%      0.0%      0.0%
 flops     5 x     5 x     5             92947500      74.4%      0.0%     25.6%
 flops   100 x   100 x   100          20756000000     100.0%      0.0%      0.0%
 flops inhomo. stacks                           0       0.0%      0.0%      0.0%
 flops total                        20.914688E+09      99.9%      0.0%      0.1%
 flops max/rank                      7.609727E+09      99.9%      0.0%      0.1%
 matmuls inhomo. stacks                         0       0.0%      0.0%      0.0%
 matmuls total                             385455      75.3%      0.0%     24.7%
 number of processed stacks                  4470      92.8%      0.0%      7.2%
 average stack size                                    70.0       0.0     297.3
```

Moreover, the matrix multiplications run on the CUDA backend in these two tests always have sizes with `m = n = k`. 

Could we add some additional multiplications to these two tests which make heavier use of `libcusmm` and also test cases where `m = n = k` is not true?

**Comment by hfp** [comment]
I wonder if a compile-time option can help which forces a specific backend (ignoring any thresholds or heuristics that may pick one over another backend)? Or more specific, is there anything that prevents to run cuSMMs in certain cases?

**Comment by alazzaro** [comment]
@shoshijak Thanks for pointing out this issue. Yes, you are right, those tests are not meant for testing the blocks, rather for the entire DBCSR infrastructure. Anyway, this is can be fixed in the future by adding a new test with more reasonable block sizes. Note that the current CI doesn't test the GPU anyway...

@hfp No, there is nothing to decide if it is worth to run on the GPU or not. Basically, by setting the ACC macro at compiling time we force everything to run on the GPU. For instance, it can happen that the GPU implementation is slower than the CPU-only one. The current policy is that the user has to run both implementations and decide what to run. We can introduce some heuristics to decide at runtime what goes to the GPU/CPU, however this is not a priority for the moment...

**Comment by shoshijak** [comment]
@alazzaro even though the current CI doesn't test the GPU-backend, having a more complete DBCSR unit test would be advantageous, be it only for local testing. 
Do you see any downside to adding some "more reasonable block sizes" to the test?

**Comment by alazzaro** [comment]
@shoshijak Sure, we can add a unittest3 which changes the block sizes and use the current unittest infrastructure.

**Comment by alazzaro** [comment]
Is this issue closed now that PR #132  has been merged?

**Comment by shoshijak** [comment]
Yes, sorry, I thought it would close it automatically

**Comment by dev-zero** [comment]
@shoshijak [for future reference](https://help.github.com/articles/closing-issues-using-keywords/) ;-)
