### ISSUE TITLE
USE libxsmm without ONLY in dbcsr_toollib.F

### ISSUE THREAD

**Issue by mkrack** [cp2k/dbcsr#133]
/home/krack/github/mkrack_f2008/cp2k/exts/dbcsr/src/utils/dbcsr_toollib.F:208:10:

   USE libxsmm
      1

Warning: USE statement at (1) has no ONLY qualifier [-Wuse-without-only]

**Comment by dev-zero** [comment]
@hfp  Introduced in dc17ef00436d8a00f88feea7f2d2e43a2f43b47c, could be restricted to `USE libxsmm, ONLY: libxsmm_hash` or am I missing something?

**Comment by alazzaro** [comment]
I think so, it is an easy fix. Note that it is part of our conventions (see https://github.com/cp2k/dbcsr/blob/develop/CONTRIBUTING.md ), even if we don't enforce them...
At this point, DBCSR is more relaxed than DBCSR...

**Comment by mkrack** [comment]
No doubt, easy to fix, just wanted to leave it to the DBCSR developers if they want to follow such convention.
