### ISSUE TITLE
DBCSR hangs with OpenMPI >= 3.1.0

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#141]
given that there are now several releases of OpenMPI >= 3.1.0 we may have to investigate to either fix the problem on our side (if there is one) or report an issue upstream with minimal reproducer

**Comment by alazzaro** [comment]
As reported here https://github.com/cp2k/cp2k/issues/441#issuecomment-505941960, the problem seems fixed with OpenMPI 4.0.1

**Comment by alazzaro** [comment]
Closed via #307.
