### ISSUE TITLE
[libcusmm] check Python dependencies in requirements.txt

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#167]
We get another security warning by GitHub for one of the packages mentioned in our `requirements.txt` (`jinja2==2.10`). This should be fixed, mostly since it is annoying.

Grepping  the code only shows `jinja2` in the `requirements.txt` but no usage in any other file, the same for other packages on the list, like `kiwisolver`, `cycler`, etc.

Could we reduce the `requirements.txt` to the direct dependencies only?

**Comment by alazzaro** [comment]
I still get the security alert on  src/acc/libsmm_acc/libcusmm/notebooks/requirements.txt
Is this expected?

**Comment by shoshijak** [comment]
I'm sorry, I fixed the warning in `src/acc/libsmm_acc/libcusmm/requirements.txt` and oversaw `src/acc/libsmm_acc/libcusmm/notebooks/requirements.txt`. 
I'll fix this.
