### ISSUE TITLE
Add #threads, #ranks to DBCSR outputs

### ISSUE THREAD

**Issue by shoshijak** [cp2k/dbcsr#173]
DBCSR provides all sorts of useful information at the start of a run (cf `src/core/dbcsr_config.F`). It would be terrific if it could provide parallelisation information such as number of threads and number of MPI ranks as well, as is provided, for example, when running the performance driver. 

This would be extremely useful for improving readability when performance debugging and would also help detecting issues such as the one solved in #158. 

As I'm not sure in which part of the code base this should be added and my Fortran skills are suboptimal, I'm opening this as an issue.

**Comment by alazzaro** [comment]
Yes, good point. Ilia (@dithillobothrium ) is working on including a global communicator in the dbcsr_config (see #171 )

**Comment by shoshijak** [comment]
Oh great, thanks for the quick response!

**Comment by shoshijak** [comment]
@dithillobothrium, now that #171 is merged, is this proposed enhancement easy to implement?
