### ISSUE TITLE
Remove path dependency in the GPU kernel generation

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#19]
@shoshijak 
Currently, we are hard-coding the path to the kernels (in the file libcusmm.cpp) by setting the external macro DBCSRHOME. 

#define KERNEL_FILES_PATH DBCSRHOME "/src/acc/libsmm_acc/libcusmm/kernels/"

The reason for that is because we set the include directory:

const std::string kernel_files_path = KERNEL_FILES_PATH;
const std::string include_opt = "-I=" + kernel_files_path;

The only header I see is cusmm_common.h, which is a bunch of macro definitions.
Would it be possible to hack the 

generate_kernels.py

and embed the entire cusmm_common.h in a variable, such that we don't need any include (and path) anymore? Then we can obtain the kernel codes by adding the header string  + the kernel string...

**Comment by alazzaro** [comment]
As a workaround, I have introduced a new variable:

DBCSRINC

which can be set in the Makefile.inc. The default value is:

DBCSRINC ?= $(SRCDIR)/acc/libsmm_acc/libcusmm/kernels/

(see Makefile)

**Comment by shoshijak** [comment]
Fixed in PR#26
