### ISSUE TITLE
Replace MATMUL and TRANSPOSE

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#190]
We have some MATMUL and TRANSPOSE that can be optimized with GEMM calls that we can probably optimize (with LIBXSMM or MKL?)

**Comment by hfp** [comment]
Libxsmm 1.11 (current v1.12.1) significantly improved/updated support for CRAY Compiler (CCE).

**Comment by alazzaro** [comment]
Update: 
The MATMUL part is fine.
TRANSPOSE functions are in block/:

dbcsr_block_access.f90
dbcsr_block_operations.F
dbcsr_block_operations.f90

Thanks to @hfp for the dbcsr_block_operations.f90 done!
Still need to complete the other two files...

**Comment by alazzaro** [comment]
Analyzing the remaining TRANSPOSE, they are not in a critical part of the code (only 2D arrays, which don't use that often anyway). Closing the issue.
