### ISSUE TITLE
Should we consider FPE during testing?

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#194]
Should we add -ffpe-trap for testing? Probably only for Makefile.inc when CHECKS=1.

**Comment by oschuett** [comment]
Yes, please do. FPEs are a powerful and cheap debugging tool, but it only works when the code is generally exception free. In CP2K we enable them for dbg builds.

**Comment by hfp** [comment]
yes, also some other flags from CP2K's test-builds are useful e.g., runtime check if temporary arrays were created.

**Comment by alazzaro** [comment]
Done via #307
