### ISSUE TITLE
Cannot make with GPU flag enabled

### ISSUE THREAD

**Issue by tmhuysen** [cp2k/dbcsr#196]
**Describe the bug**
My computer crashes during make.
**To Reproduce**
1. After fresh clone run make: `make GPU=1`
2. Was ran in unix
3. No error is produced, the crash prevent me from logging the make output.

**Expected behavior**
I expected my computer to not crash.

**Environment:**
 - Operating system & version : macOS High Sierra version 10.13.6
 - Compiler vendor & version : GNU Fortran (MacPorts gcc8 8.3.0_4) 8.3.0
 - Build environment (make or cmake) : make
 - Configuration of DBCSR (either the cmake flags or the `Makefile.inc`) : GNU=1, MPI=0
 - If CUDA is being used: CUDA version and GPU architecture : CUDA Driver Version: 418.168, Cuda compilation tools, release 10.1, V10.1.168, NVIDIA GeForce GT 750M 2048 MB
 - BLAS/LAPACK implementation and version : MKL 2019.2.184 (intel)

**Additional Notes**

`make MPI=0 CHECKS=1 CINT=1`
Does not result in issues.

**Comment by alazzaro** [comment]
sorry, you don't see the error and make is crashing?
HAve you adapted Makefile.inc to your system?

**Comment by alazzaro** [comment]
I'm closing because of missing info. Please reopen and provide info.
