### ISSUE TITLE
Bug in dc_memzero_cu

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#229]
Reported by @dithillobothrium 

The function shifts the lower bound first_byte to match C index:

https://github.com/cp2k/dbcsr/blob/b74fd48df581ea04c58e64275a92efb9c1f7d97b/src/acc/dbcsr_acc_devmem.F#L459

However the function is called at: 

https://github.com/cp2k/dbcsr/blob/b74fd48df581ea04c58e64275a92efb9c1f7d97b/src/block/dbcsr_block_operations.F#L1265

already with a shifted value. Therefore we have to call the function with `s*l+1`.

**Comment by hfp** [comment]
Should this issue be resolved for v2.0 i.e., CP2K release?

**Comment by alazzaro** [comment]
v2.1, just after v2.0, in time for CP2K release...

**Comment by hfp** [comment]
@alazzaro Thank you!  Btw, there is still some potential that issue #214 works out (not sure if in time for DBCSR v2.1). I have essentially finished the backend. Now, the fun part is to get it working in terms of build system, integration with DBCSR and CP2K, and also to get it doing something with at least iGPU.

**Comment by alazzaro** [comment]
v2.0 would be rc9 (current master) as soon as the dashboard will be happy.
This release is for the Tensor part and ultimately it would be the minimum version for the new CP2K release. Then, we will start to push stuff for v2.1... deadline for that will be the CP2K release (if needed)...

**Comment by alazzaro** [comment]
Closing this issue, fixed via #269
