### ISSUE TITLE
Include a version file of the library

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#24]
@dev-zero is suggesting to have it in the build system

**Comment by dev-zero** [comment]
The build system needs the version the latest when either building a release tarball, a binary package or a shared library (for the `soname` and the file name). It is therefore usually easier to keep the version only in the build system and pass it further down using either a config header `dbcsr_config.h` (which could then also include oder pre-processor definitions) or directly preprocessor definitions.
There may be other build steps where you may need the version, like the documentation.
