### ISSUE TITLE
[cmake] DBCSR as external library

### ISSUE THREAD

**Issue by ambmax00** [cp2k/dbcsr#246]
Hi,
I have a few problems getting cmake to integrate the installed DBCSR library into my project:
```
cmake_minimum_required(VERSION 3.10 FATAL_ERROR)  

project(project CXX)`

set(CMAKE_BUILD_TYPE Release)

set(DBCSR_DIR /path/to/dbcsr/install/lib/cmake/dbcsr/)

find_package(MPI REQUIRED)
find_package(DBCSR REQUIRED)

include_directories(/path/to/dbcsr/install/include/)

set (CMAKE_CXX_FLAGS "-lgfortran")

add_executable(
        project
        test.cpp
)

target_link_libraries(
        project
        ${MPI_LIBRARIES}
        DBCSR::dbcsr_c
)
```

This leads however to the following errors:
```
--- Configuring done
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "project" links to target "OpenMP::OpenMP_Fortran" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:16 (add_executable):
  Target "project" links to target "MPI::MPI_Fortran" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:16 (add_executable):
  Target "project" links to target "MPI::MPI_C" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
```

Are there any other ways to include it using cmake? Maybe as external project?
Any help would be appreciated.

**Comment by dev-zero** [comment]
Please note: setting `include_directories` is not necessary, neither is setting a variable `DBCSR_DIR`.

After installing `dbcsr` to a location using `make DESTDIR=/tmp/dbcsr install` the following MWE works here:

```cmake
cmake_minimum_required (VERSION 3.10)

project(foo)

enable_language(Fortran)

find_package(DBCSR 2.0.0 CONFIG REQUIRED)

add_library(foo foo.F90 foop.F90 bar.f90)
target_link_libraries(foo DBCSR::dbcsr)
```

when calling CMake with `CMAKE_PREFIX_PATH=/tmp/dbcsr/usr/local/lib64/cmake cmake ..`
(use the path were you installed DBCSR to).

For C/C++ the following has been verified to work:

```cmake
    add_executable(dbcsr_example_c dbcsr_example.c)
    target_link_libraries(dbcsr_example_c DBCSR::dbcsr_c MPI::MPI_C)
    
    add_executable(dbcsr_example_cpp dbcsr_example.cpp)
    target_link_libraries(dbcsr_example_cpp DBCSR::dbcsr_c MPI::MPI_CXX)
```

given the respective language was enabled using `enable_language`.

If this doesn't help, please give us more details on the platform you're running (OS, distribution, etc.), the CMake version and the DBCSR version.

**Comment by ambmax00** [comment]
Ok, it works! Thanks for the help.

**Comment by dev-zero** [comment]
you're welcome. I've added the documentation to the `README.md` for future reference: https://github.com/cp2k/dbcsr#using-dbcsr-in-a-cmake-project
