### ISSUE TITLE
Make CUBLAS the responsibility of `libsmm_acc` and simplify compile options

### ISSUE THREAD

**Issue by shoshijak** [cp2k/dbcsr#254]
In the current state of DBCSR:
1. There are two separate compilation options `-DUSE_CUDA=<OFF|ON>` and `-DUSE_CUBLAS=<OFF|ON>`.
2. In DBCSR code, the macro `__DBCSR_ACC` can take values `1`, `2`, `3` depending on whether 1) CUBLAS and HIP both disabled, 2) CUBLAS is enabled, 3) HIPBLAS is enabled.
3. CUBLAS is handled by DBCSR (see, e.g. [these lines](https://github.com/cp2k/dbcsr/blob/develop/src/mm/dbcsr_acc_operations.F#L142-L171) and [this line](https://github.com/cp2k/dbcsr/blob/develop/src/core/dbcsr_config.F#L13)), while libsmm_acc knows nothing of CUBLAS.

There are a few issues with this:
1. There is no good reason for the two separate compile options `USE_CUDA` and `USE_CUBLAS`, because:
  - any user who has CUDA installed will have CUBLAS installed as well, and compiling DBCSR with CUDA support but without CUBLAS does not make sense from a functionality point of view nor from a performance point of view.
  - having two options for the CUDA backend instead of one makes things unnecessarily complicated

2. `__DBCSR_ACC` is obscure

- The values that can be taken by `__DBCSR_ACC` aren't well documented in DBCSR nor in CP2K (see, e.g. [this issue](https://github.com/cp2k/cp2k/issues/577)).

3. Separation of concerns isn't well enforced 

I would like to:

1. & 2. Automatically and always enable CUBLAS when CUDA is enabled

- remove cmake compilation option `USE_CUBLAS` and just always enable CUBLAS when CUDA is enabled
- remove macro values `__DBCSR_ACC=2` (and `__DBCSR_ACC=3` with HIP) and just always enable CU/HIPBLAS when CUDA/HIP is enabled

3. Make CU/HIPBLAS the responsibility of `libsmm_acc`

- this is better from the point of view of separation of concerns: `libsmm_acc` handles all of the GPU acceleration, including CU/HIPBLAS.
- Remove the additional round trip to Fortran in dbcsr_acc_operations.F. Really, libsmm_acc should simply call cublas directly.
- libsmm_acc should handle deciding whether to multiply a block using its custom kernels or cublas, instead of leaving this decision up to DBCSR's Fortran code as is currently the case
- this means less code because we could remove dbcsr/src/acc/cublaswrap/. And it
would also make responsibilities clearer as the Fortran code would no longer have to deal with the different ways to feed the GPU.
- (these last points are input from @oschuett , thanks by the way!)

---

To Do:

- [ ] start factoring out grouped commands to included files instead, similar to the CompilerConfiguration.cmake.

**Comment by alazzaro** [comment]
A fast reply, for the moment.
Please, note that CUBLAS support is still experimental (this answer to your question in https://github.com/cp2k/cp2k/issues/577 ), so any suggestions on how to update it are welcome. Your point to drop a macro is correct, at the beginning the idea was to have a way to test the code without changing the arch files in CP2K (you have to add cublas library).
Then, concerning performance, it turns out that GPU densification can slowdown performance for some CP2K tests, that's why we have 

#if !defined (__DBCSR_ACC) || (__DBCSR_ACC == 2)
      LOGICAL  :: mm_densification = .TRUE.
#else
      LOGICAL  :: mm_densification = .FALSE.
#endif

(see https://github.com/cp2k/dbcsr/blob/118f2157e9b499a0705c0610f84968493c684acf/src/core/dbcsr_config.F#L99-L103)

The densification parameter can be changed at runtime.
So, I like the idea to make densification by default (therefore using cublas), but this changed the default in CP2K and we have to test it...

If you agree, I will mark this issue for the v3.0 milestone.

**Comment by dev-zero** [comment]
> 1. & 2. Automatically and always enable CUBLAS when CUDA is enabled
> * remove cmake compilation option `USE_CUBLAS` and just always enable CUBLAS when CUDA is enabled

The `CUBLAS` flag (in whatever form) is a remnant of the past AFAIK when `CUBLAS` was not considered stable/mature enough (and was not always available?). If that is not the case anymore then it can go.
When creating the CMake build system I tried to mimic the previous Makefile. When doing so I thought having two booleans (`USE_CUDA` and `USE_CUBLAS`, the latter conditional) would be easier to manage in CMake than having a tri-state (`DBCSR_ACC`).

> 1. Make CU/HIPBLAS the responsibility of `libsmm_acc`
> 
> * this is better from the point of view of separation of concerns: `libsmm_acc` handles all of the GPU acceleration, including CU/HIPBLAS.
> * Remove the additional round trip to Fortran in dbcsr_acc_operations.F. Really, libsmm_acc should simply call cublas directly.
> * libsmm_acc should handle deciding whether to multiply a block using its custom kernels or cublas, instead of leaving this decision up to DBCSR's Fortran code as is currently the case
> * this means less code because we could remove dbcsr/src/acc/cublaswrap/. And it
>   would also make responsibilities clearer as the Fortran code would no longer have to deal with the different ways to feed the GPU.

Sounds reasonable given the current ecosystem. Might bite us when the dedicated Intel GPUs come around if they don't provide the same level of functionality from the start. If I understood it correctly: at the moment we could for example fallback to CPU-BLAS inside Fortran code while in this way we would have to provide missing CPU-based functionality in C.

**Comment by dithillobothrium** [comment]
From my point of view densification works fine. I think it makes sense to make it default, reduce the code and move CUBLAS call it in libcusmm.

> but this changed the default in CP2K and we have to test it...
If all the multiplications are working then it changes nothing. Isn't it so?

**Comment by alazzaro** [comment]
I think this issue is mostly done, right? @shoshijak

**Comment by shoshijak** [comment]
Yes, I agree

**Comment by alazzaro** [comment]
closed via #381
