### ISSUE TITLE
rename acc_init function

### ISSUE THREAD

**Issue by hfp** [cp2k/dbcsr#261]
Rename `acc_init` (ACC interface) as this name conflicts when using Cray Compiler (CCE). It appears OpenACC is enabled by default but has a similar prototype/symbol. The hint about this issue is a relatively unspecific warning message:

```text
A declaration for library function acc_init is invalid.
```

Perhaps `dbcsr_` should used instead or in addition of/to `acc_`. The solution may also impact CP2K.

**Comment by hfp** [comment]
I guess this should be resolved for 2.0?

**Comment by alazzaro** [comment]
Adding `dbcsr_` namespace it is always a good idea (we enforce this policy for the API functions).
Concerning CCE, I think we don't see the problem in the dashboard because we don't use it in combination with the ACC. As far I can tell, we don't use it on the CI with the ACC either.

So, at this point, I think you want to have ACC enabled with CCE? Personally, I would not support it (CCE is used for testing, no for production). The current ACC-GPU support is GNU or Intel+CUDA.

Moving ahead, the rename of the function can be a good idea. Probably it can be related to what @shoshijak is doing with #241 ?

**Comment by alazzaro** [comment]
> I guess this should be resolved for 2.0?

Well, CCE+GPU is not supported, so I would not consider the fix for 2.0... let's keep it for 2.1

**Comment by hfp** [comment]
Makes sense. Alternatively (or in addition), we could figure out the `-h` setting to disable OpenACC when using CCE/Cray. It is definitely a concern wrt GPU support to have a symbol clash like this.

**Comment by alazzaro** [comment]
Well, the flag is

`-hnoacc`

I agree, that's the easiest way, let's keep the issue open for future discussion.
For the time being, could you update the CCE flag in the CI?
I will update the dashboard...

**Comment by hfp** [comment]
ACK, will do!

**Comment by hfp** [comment]
I will update `cmake/CompilerConfiguration.cmake` to include `-hnoacc`. Btw, I am testing this on Archer.

**Comment by alazzaro** [comment]
OK, perfect!
Actually, Archer has a pretty old CCE version (up to 8.7.7). With the CCE 9.x (based on LLVM) some of the flags, such as OpenMP, are off by default... Do we consider such a case, @dev-zero ?

**Comment by hfp** [comment]
Indeed, I use the "latest" 8.7.7.

**Comment by hfp** [comment]
Hmm, apparently `-hnoacc` is not sufficient at least wrt to the warning. I will disable OpenACC and also suppress CC-1234: `-hnoacc -M1234`. Will try.

**Comment by dev-zero** [comment]
@alazzaro yes, we're using CMake's facilities to add the dependency for OpenMP which makes it completely transparent for us by simply using `target_link_libraries(dbcsr PRIVATE OpenMP::OpenMP_Fortran)`. Whether the CMake "sanitizes" the compiler invocation (in the sense that we do not automatically build with OpenMP unless requested on compilers which have it automatically enabled) is something I haven't check (yet).

**Comment by alazzaro** [comment]
> Hmm, apparently `-hnoacc` is not sufficient at least wrt to the warning. I will disable OpenACC and also suppress CC-1234: `-hnoacc -M1234`. Will try.

Then it seems a bug of the compiler... I will try on Daint with a new version of the compiler, for the time being your solution is fine... If it doesn't work, then the only way is to change name, pretty annoying...
