### ISSUE TITLE
Remove makefile from the official documentation

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#263]
Since CMake will be the official way to compile the library, and makefile will be only considered for CP2K compilation, I propose to drop any Makefile mention in the documentation and move the Makefile and Makefile.inc within a `.make` directory, leaving the requirement to update Makefile.inc for the developers who want any new feature to be used in CP2K. 

Furthermore, we will still use the makefile for coverage and some testings...

**Comment by dev-zero** [comment]
wrt coverage: CMake accepted [my tiny patch](https://gitlab.kitware.com/cmake/cmake/merge_requests/4048#note_653427) which fixes building with `fypp -n` together with ninja and is now in their nightly release for 3.17.0 :)
So, my plan is to switch to cmake-nightly for the Travis-CI and ninja for the coverage (keeping make for the rest to ensure we don't break any of the two).

**Comment by alazzaro** [comment]
Great! We will keep make because of CP2K and we need to test it. I will flag this issue as v2.1 then...

**Comment by alazzaro** [comment]
https://github.com/cp2k/dbcsr/pull/241#issuecomment-557037969

**Comment by alazzaro** [comment]
Current Makefile serves for
- [ ] Pretty. We can move it to pre-commit (see https://github.com/cp2k/dbcsr/pull/270#issuecomment-558139568 )

- [ ] Aggressive debugging flags

- [ ] Coverage (see #273)

This is the `make help` output:
```
=================== Default ====================
libdbcsr                     Build DBCSR library

=================== Binaries ====================
all                          Builds all executables
dbcsr_performance_driver     
dbcsr_tas_unittest           
dbcsr_tensor_unittest        
dbcsr_test_csr_conversions   
dbcsr_unittest1              
dbcsr_unittest2              
dbcsr_unittest3              

===================== Tools =====================
pretty                       Reformat all source files in a pretty way
prettyclean                  Remove prettify marker files

================= Other Targets =================
version                      Print DBCSR version
toolversions                 Print versions of build tools
toolflags                    Print flags used with build tools
install                      Install the library and modules under PREFIX=<directory> (default /Users/alazzaro/Work/dbcsr/v2/dbcsr/install)
test                         Run the unittests available in tests/
clean                        Remove intermediate object and mod files, but not the libraries and executables
realclean                    Remove all files
help                         Print this help text
================= Variables =====================
For convenience, some variables can be set during compilation,
e.g. make VARIABLE=value (multiple variables are possible):
MPI=0    : disable MPI compilation
GNU=0    : disable GNU compiler compilation and enable Intel compiler compilation
CHECKS=1 : enable GNU compiler checks and DBCSR asserts
CINT=1   : generate the C interface
GPU=1    : enable GPU support
```

**Comment by alazzaro** [comment]
Starting to drop makefile support, leaving it only for CP2K inclusion.
Create branch https://github.com/cp2k/dbcsr/tree/makefile_drop

**Comment by alazzaro** [comment]
Partially done via #307 
Still need to consider pretty.

**Comment by dev-zero** [comment]
> Partially done via #307
> Still need to consider pretty.

done, running pre-commit now triggers fprettify

**Comment by pseewald** [comment]
> > Partially done via #307
> > Still need to consider pretty.
> 
> done, running pre-commit now triggers fprettify

Shall we consider running `fprettify` with the same flags as in CP2K? I recommended less aggressive flags before but only because I found `make pretty` annoying, now that it's fully integrated, I think we could also use full whitespace formatting.

**Comment by alazzaro** [comment]
So, I'm not sure I understand the point here.
The old "make pretty" was based on

```
$(TOOLSDIR)/fprettify/fprettify.py --disable-whitespace $1
```

Now, the pre-commit uses the command without --disable-whitespace, so is it what @pseewald is proposing? If so, we can just run pretty with spaces and commit all the changed files at once so that the repo is updated.

**Comment by alazzaro** [comment]
@dev-zero It seems that the pre-commit has to download the submodule to access prettifier.

**Comment by dev-zero** [comment]
With the pre-commit integration we could leave it to pre-commit to pull fprettify instead of having it as a submodule. Opinions?

**Comment by alazzaro** [comment]
OK, I like the idea. Let's do step by step:
1. Patrick is doing a new fpretty release that we will use in the pre-commit (Patrick)
2. we check out the fpretty release and run in the pre-commit (Tiziano)
3. Alfio will update the submodule to the new release, run a pretty with space, remove all references to pretty (old Makefile and documentation) and commit it (Alfio)

Sounds a good strategy?

**Comment by pseewald** [comment]
I created a new release (v0.3.6)

**Comment by dev-zero** [comment]
> OK, I like the idea. Let's do step by step:
> 
>     1. Patrick is doing a new fpretty release that we will use in the pre-commit (Patrick)
> 
>     2. we check out the fpretty release and run in the pre-commit (Tiziano)
> 
>     3. Alfio will update the submodule to the new release, run a pretty with space, remove all references to pretty (old Makefile, submodule, and documentation) and commit it (Alfio)

The new pretty is already run and changes checked in.

**Comment by alazzaro** [comment]
@dev-zero OK, I did pretty in my last commit and found the reason for the difference with the makefile: makefile applies pretty to src and tests directories, while pre-commit does only for src. Could you extend it and include examples too?

**Comment by alazzaro** [comment]
This is definitely done now (26d58eefa51c6612f617e2fe901b360503fd4a4b)
Thanks @dev-zero and @pseewald !
