### ISSUE TITLE
Building fails with CMake 3.10.2 due to setting properties in OBJECT libraries

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#266]
the error message:
```
CMake Error at src/CMakeLists.txt:250 (target_link_libraries):
  Object library target "acc" may not link to anything.
```

with the culprit here:
https://github.com/cp2k/dbcsr/blob/a74a9fd5e3b07204812ee29b870468e8d2cd4285/src/CMakeLists.txt#L248-L253

CMake 3.10 does not properly support `target_link_libraries` on OBJECT libraries.

We already have a workaround for similar issues in pre 3.12 CMake here:

https://github.com/cp2k/dbcsr/blob/a74a9fd5e3b07204812ee29b870468e8d2cd4285/src/CMakeLists.txt#L256-L260

@shoshijak we have two options: continue to workaround it or enforce upgrading to CMake >= 3.12. The problem is that we don't test with 3.10 anymore as it seems, so it wasn't caught.

**Comment by shoshijak** [comment]
I see ... 

> @shoshijak we have two options: continue to workaround it or enforce upgrading to CMake >= 3.12. The problem is that we don't test with 3.10 anymore as it seems, so it wasn't caught.

Do we have any good/important reason to support cmake 3.10? 
If not, I'd suggest we drop it and enforce to cmake >= 3.12. Otherwise, we'd just bbe loading up our CMakeLists with more and more workarounds ...

**Comment by dev-zero** [comment]
SUSE SLE and openSUSE Leap 15 are still on CMake 3.10 (so, compilation is broken on our systems for now, at least with CUBLAS), Centos 6 and older RHEL probably as well (Centos 7 has 3.14 though) and Ubuntu 18.04 LTS is also stuck at 3.10.

**Comment by alazzaro** [comment]
I would like to add that default on all cray system is 3.10 too...
I think we have to still support 3.10...

**Comment by shoshijak** [comment]
After a quick lookup in cmake's documentation, it seems that if we want to keep cmake 3.10, the fix would be: 

> Although object libraries may not be named directly in calls to the target_link_libraries() command, they can be “linked” indirectly by using an Interface Library whose INTERFACE_SOURCES target property is set to name $<TARGET_OBJECTS:objlib>.

from: https://cmake.org/cmake/help/v3.10/manual/cmake-buildsystem.7.html#object-libraries. 
Seems a little cumbersome but not too difficult. 

I would much rather upgrade to cmake 3.12 to avoid adding on workarounds and because, as you say, individual upgrading of cmake is not hard. But if you strongly feel that DBCSR should support cmake 3.10, I'll fix this.

**Comment by dev-zero** [comment]
@shoshijak we already have the workarounds in other places, for example here: https://github.com/cp2k/dbcsr/blob/c81cff1b21e614bd64b75b621e01d666b404ebf2/src/acc/libsmm_acc/CMakeLists.txt#L75-L81

**Comment by dev-zero** [comment]
Given that Cray is also on 3.10 (due to SLE inheritance) I would prefer if we could stay at 3.10 for a little while longer. The Daint CI can also be tuned (by removing the CMake module from the list of modules to load) to prevent regressions

**Comment by shoshijak** [comment]
Okay, makes sense. I'll try to fix this today.
