### ISSUE TITLE
HIP-DBCSR broken with CP2K

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#271]
DBCSR with latest changes to enable HIP doesn't work when tested with CP2K, see

https://www.cp2k.org/static/regtest/trunk/cscs-daint-xc50_gpu/CRAY_XC50-gfortran_gpu.psmp.out

The DBCSR is based on latest @shoshijak 's commit (https://github.com/cp2k/dbcsr/commit/a74a9fd5e3b07204812ee29b870468e8d2cd4285).

For the arch file, I've added `-D__CUDA` as described in the Makefile.inc.
I think, the failing test is `UNIT/libcp2k_unittest` with a memory corruption.

@shoshijak could you take a look?

Furthermore, I've noticed that some files in .gitignore haven't updated:

```
 > git st
HEAD detached at a74a9fd5
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	src/acc/libsmm_acc/parameters.h
	src/acc/libsmm_acc/smm_acc_kernels.h

```

I think we need to update the lines

https://github.com/cp2k/dbcsr/blob/02b84615b89d4ffea953d3f6c25ecea5e917fbfc/.gitignore#L6-L8

**Comment by shoshijak** [comment]
thanks for reporting, I'll look into it ... !

**Comment by dev-zero** [comment]
@shoshijak can you please move those entries to a local `.gitignore` while at it?

**Comment by hfp** [comment]
The function `acc_memcpy_d2h` uses a wrong enumerator: `MemcpyHostToDevice` rather than `MemcpyDeviceToHost`.

---
Unrelated: there are also warnings on Cray about verbose format flags, and some of the translation units contain tabs/ws mixture.

**Comment by shoshijak** [comment]
> The function acc_memcpy_d2h uses a wrong enumerator: MemcpyHostToDevice rather than MemcpyDeviceToHost.

@hfp thanks a lot for catching this!

**Comment by shoshijak** [comment]
I'm now concerned by the fact that my PR passed all tests, despite this mistake.

**Comment by hfp** [comment]
@shoshijak The OpenMP/offload PR brings a test purely based on the ACC interface. It can/will test every backend. I am planning to make the CUDA/HIP tests also not backend specific. I think for instance the transpose test could just use a different include-path for the "parameters" and stick with fixed triplets for non-CUDA/HIP.

**Comment by dev-zero** [comment]
@shoshijak don't be, that's normal in a project of this complexity and limited amount of tests. The solution is to come up with a unittest to reproduce the error seen in CP2K...

**Comment by hfp** [comment]
I think the afore mentioned test already ran into this:
https://github.com/hfp/dbcsr/blob/openmp_acc/tests/CMakeLists.txt#L84

However, I did not knew at that time about the typo in the CUDA backend and was thinking it's somehow a problem along by bits...

**Comment by alazzaro** [comment]
For the record, CP2K passed all reg-tests on Daint with this DBCR fix.
