### ISSUE TITLE
Shared Library and library/symbol versioning support

### ISSUE THREAD

**Issue by mbanck** [cp2k/dbcsr#283]
The non-CMake Makefile seems to have minimal support for building a shared libray by passing `LD_SHARED` to make.

However, in order for DBCSR to be (more) useful for external projects, proper shared library support with library versioning (SONAME-handling) would be desirable. I understand that this is non-trivial in CMake due to its (if I am still current) pretty bad support for library versioning, but it should pay off for the future. Also, it requires a certain API/ABI stability, which I am not sure is the case already for DBCSR as I did not follow development closely.

In addition, adding symbol versioning from the start should make it possible to transition between different DBCSR versions more easily for external projects.

**Comment by dev-zero** [comment]
Good point. We're already follow semantic versioning for the package version such that changes to existing APIs trigger a major version change (1.x.x -> 2.0.0) while additions to the API require only a minor version change. Although I'm not fully convinced that it's a good idea to tie the library (API or ABI) version to the package version, the easiest way to start would still be to include the major project version in the soname.

See for discussions:
* https://autotools.io/libtool/version.html
* https://github.com/pvanhoof/dir-examples
* an example: http://mongocxx.org/mongocxx-v3/api-abi-versioning/

... and several threads on reddit or hackernews.

**Comment by dev-zero** [comment]
@mbanck I hope this is what you requested, if not, please reopen the issue

**Comment by mbanck** [comment]
It certainly helps, thanks! I will try to take a look later on.

I guess it would be easier if a minor version change wouldn't change soname, but as long as DBCSR isn't widely (yet) used it should not be a practical problem.

**Comment by dev-zero** [comment]
yes, we discussed the issue of which version to include: for now we decided to include the minor version as well since we can't guarantee API stability just yet.
