### ISSUE TITLE
CP2K Multi GPU - Multiple GPU contexts created on GPU 0

### ISSUE THREAD

**Issue by LStuber** [cp2k/dbcsr#292]
**Summary:**

When running the GPU version of CP2K in MPI and multiple GPUs, some undesirable (?) processes are created on GPU 0.

The problem comes from the acc_init function of DBCSR. I noticed it has been removed in the develop branch of DBCSR, but is still in the one CP2K installs. So I want to make sure the issue is known.

**Example:** (nvidia-smi)

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      5657      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp   305MiB |
|    0      5658      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp   305MiB |
|    0      5660      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
|    0      5661      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp   305MiB |
|    0      5665      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp   305MiB |
|    0      5666      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp   305MiB |
|    0      5669      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp   305MiB |
|    0      5670      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp   305MiB |
|    1      5657      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
|    2      5658      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
|    3      5661      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
|    4      5665      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
|    5      5666      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
|    6      5670      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
|    7      5669      C   ...ug-builds/cp2k/exe/local_cuda/cp2k.psmp  1025MiB |
+-----------------------------------------------------------------------------+
```

The additional contexts on GPU 0 are undesirable, they cause approximately 5% performance loss and cause some test cases to OOM.

The problem comes from the acc_init function, more precisely from this line:

https://github.com/cp2k/dbcsr/blob/e4db53ef9f983fcfda72edc747d598935038b77d/src/acc/cuda/acc_cuda_init.cu#L37

Which gets the device number 0 instead of the current device number and then proceeds to create a context on it . There are multiple ways to solve it, in my case I just commented out acc_init.

**To Reproduce:**

* Build MPI-enabled, cuda-enabled CP2K.
* Run mpirun -n 8 cp2k.psmp
* The issue will be hidden if you restrict CUDA_VISIBLE_DEVICES, so make sure you don't have a pre script that does the GPU binding for you.

**Comment by alazzaro** [comment]
Thanks for reporting this problem.
This was a long-standing problem, now fixed in the develop branch. Could you test it?

**Comment by alazzaro** [comment]
Closing this issue via 746e46ba667acfa8502ec90c4cfe1121292c8a1f.

**Comment by LStuber** [comment]
Can confirm, the issue is fixed
