### ISSUE TITLE
Performace: Platform diffrence of ACC_RTC_CALL

### ISSUE THREAD

**Issue by vitesselin** [cp2k/dbcsr#294]
Hi developers,

Is it possible to use the parameters passing mechanism instead of  using runtime compile (RTC). 
The performance of CUDA and HIP are different when using the CompileProgram function.
Furthermore, the performance of passing parameters into kernel may not have big performace impact.
 
For an example, if we use the same sample code in the CUDA and HIP.
```
//===========================================================================
std::string smm_acc_transpose = "                                     \n\
template < int m, int n>                                              \n\
__global__ void transpose_d(int *trs_stack, double* mat){             \n\
 __shared__ double buf[m*n];                                          \n\
 int offset = trs_stack[blockIdx.x];                                  \n\
 for(int i=threadIdx.x; i < m*n; i+=blockDim.x){                      \n\
     buf[i] = mat[offset + i];                                        \n\
 }                                                                    \n\
 syncthreads();                                                       \n\
 for(int i=threadIdx.x; i < m*n; i+=blockDim.x){                      \n\
     int r_out = i % n;                                               \n\
     int c_out = i / n;                                               \n\
     int idx = r_out * m + c_out;                                     \n\
     mat[offset + i] = buf[idx];                                      \n\
 }                                                                    \n\
}                                                                     \n\
";
```

The cost of nvrtcCompileProgram is arround 100ms.
However, we see hiprtcCompileProgram costs 5000ms.

This will make CP2K with HIP in bad performance situation.

Thanks,
Vitesse.

**Comment by shoshijak** [comment]
Hi Vitesse,

> The performance of CUDA and HIP are different when using the CompileProgram function.
> The cost of nvrtcCompileProgram is arround 100ms.
> However, we see hiprtcCompileProgram costs 5000ms.

Indeed, your observations about cost of JIT being a lot higher for HIP than for CUDA match our observations, thank you for reporting this!
By the way, this is consistent with the fact that the `hipcc` compiler is a lot slower than `nvcc`. I have not made precise measurements, but this difference is noticeable.

Since HIP is still relatively young, our hope is that this performance issue with `hiprtcCompileProgram` will be fixed sometime soon, without us having to renounce template parameters.

**Comment by alazzaro** [comment]
This is a single call to the kernel generation, assuming that you run a long simulation, this time should be negligible. AMD is aware of this problem and they are working on it. Nothing we do on our side... Closing the issue, please reopen if you think there is something we can do.
