### ISSUE TITLE
Update file headers

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#3]
Following the discussion on the CP2K-Dev ML: I think we should update the file headers at some point:

1. most of them only mention CP2K, not DBCSR specifically
2. many mention a copyright, but no license

Example from current: https://github.com/cp2k/dbcsr/blob/a6eea29afe755ac0beaa270a637ed63e0724616c/src/dbcsr_api.F#L1-L4

For the first part we need a good wording which declares DBCSR as its own project but retains the link to CP2K. For the second part I guess it would make sense to use a [SPDX License Identifier](https://spdx.org/using-spdx-license-identifier)

**Comment by oschuett** [comment]
+1 for SPDX headers. I've been contemplating this for CP2K as well.

**Comment by alazzaro** [comment]
Do we have an automatic script for that?

**Comment by dev-zero** [comment]
Something like this?

```sh
find . -iname "*.F" | xargs perl -i -0pe 's/^!-+!\n(![^\n]+!\n)+!-+!/NEW HEADER GOES HERE/sm'
```

**Comment by dev-zero** [comment]
Based on the AiiDA header file, how about the following?

```fortran
!--------------------------------------------------------------------------------------------------
! Copyright (c), the CP2K and DBCSR developers groups. All rights reserved.
! This file is part of the DBCSR library.
!
! The code is hosted on GitHub at https://github.com/cp2k/dbcsr
! For further information on the license, see the LICENSE file
! For further information please visit https://dbcsr.cp2k.org
! SPDX-License-Identifier: GPL-2.0+
!--------------------------------------------------------------------------------------------------
```

Too verbose? Drop the `hosted on`?

**Comment by dev-zero** [comment]
simplified it a bit more:
```
!---------------------------------------------------------------------------------------------------
! Copyright (c), the DBCSR developers group. All rights reserved.
! This file is part of the DBCSR library.
!
! For information on the license, see the LICENSE file
! For further information please visit https://dbcsr.cp2k.org
! SPDX-License-Identifier: GPL-2.0+
!---------------------------------------------------------------------------------------------------
```

**Comment by alazzaro** [comment]
Is this change already done?
