### ISSUE TITLE
question about wrong answers on power9

### ISSUE THREAD

**Issue by asedova** [cp2k/dbcsr#314]
Hi all-

Just noticed the warning on the main page about wrong answers with openBLAS 0.3.6 on Power9. Is 0.3.5 ok? OpenBLAS is our only way to run DBCSR on Summit (except for slow netlib)

-Thanks!

Ada

**Comment by alazzaro** [comment]
Let me try to answer this question. I assume you are using DBCSR in CP2K. Currently, CP2K uses 0.3.7. Shoshana is reporting that 0.3.6 has a problem, so I would assume that 0.3.5 is fine.
In any case, you can run (in order):
1. DBCSR tests
2. the CP2K regtests

Please note that for the OpenMP compilation you need OpenMP-enabled OpenBLAS (we do now check that as result of this PR https://github.com/cp2k/dbcsr/pull/333 ), but then you have to set

`OMP_NESTED=false`

to make sure that the results are OK. Reopen the issue if you see any problem.
