### ISSUE TITLE
Macro `__CUDA_PROFILING` doesn't compile anymore

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#318]
One of the nice features of annotating events in nvprof was based on the macro `__CUDA_PROFILING`, however the code doesn't compile anymore:

```
mpif90 -c -D__FFTW3 -D__parallel -D__SCALAPACK -D__LIBXSMM -D__ACC -D__DBCSR_ACC -D__LIBINT -D__MAX_CONTR=4 -D__LIBXC -D__ELPA -D__PW_CUDA -D__CUDA_PROFILING -O3 -g -fopenmp -mavx2 -mfma -funroll-loops -ffree-form -ffree-line-length-512 -I/home/users/alazzaro/libs/libxsmm/install/include -I/home/users/alazzaro/libs/libint-v2.6.0-cp2k-lmax-7/install/include -I/home/users/alazzaro/libs/libxc-4.3.4/install/include -I/home/users/alazzaro/libs/elpa-2019.05.001/install/include/elpa_openmp-2019.05.001/elpa -I/home/users/alazzaro/libs/elpa-2019.05.001/install/include/elpa_openmp-2019.05.001/modules -I/opt/cray/pe/fftw/3.3.8.5/broadwell/include -D__SHORT_FILE__="\"dbcsr_mm_types.F\"" -I'/cray/css/users/alazzaro/cp2k/cp2k/exts/dbcsr/src/mm/' -I'/cray/css/users/alazzaro/cp2k/cp2k/exts/dbcsr/src' dbcsr_mm_types.F90 
/cray/css/users/alazzaro/cp2k/cp2k/exts/dbcsr/src/acc/acc_stream.cpp: In function 'int acc_stream_create(void**, const char*, int)':
/cray/css/users/alazzaro/cp2k/cp2k/exts/dbcsr/src/acc/acc_stream.cpp:57:24: error: 'custream' was not declared in this scope
   nvtxNameCudaStreamA(*custream, name);
                        ^~~~~~~~
/cray/css/users/alazzaro/cp2k/cp2k/exts/dbcsr/src/acc/acc_stream.cpp:57:24: note: suggested alternative: 'CUstream'
   nvtxNameCudaStreamA(*custream, name);
                        ^~~~~~~~
                        CUstream
```

@shoshijak Is it something you can fix? 
I know that the macro is not in CMake, but it is something we probably want to have it for future performance analysis...

**Comment by shoshijak** [comment]
Yes, I think I should be able to fix it. Let me take a look ...

**Comment by alazzaro** [comment]
@shoshijak 
Any update? I would like to close the v2.1 by the end of April, it would be nice to have this issue fixed by then... Please, let me know if it is not possible, we can move it to v2.2

**Comment by shoshijak** [comment]
Hi @alazzaro thank you for the reminder, I should be able to fix this next week!

**Comment by alazzaro** [comment]
https://github.com/cp2k/dbcsr/pull/340#issuecomment-617015093

**Comment by dev-zero** [comment]
I believe we have in principle 2 options:

* separate CMake variable/option to control `__CUDA_PROFILING`
* a `CUDA_PROFILING` (or general `PROFILING`) `CMAKE_BUILD_TYPE`, in `cmake/CompilerConfiguration.cmake` one would add for this a `set(CMake_Fortran_FLAGS_PROFILING "-D__CUDA_PROFILING")` and in `CMakeLists.txt` extend the enum of allowed configs
