### ISSUE TITLE
ACCFLAGS and OpenMP

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#327]
For OpenMP and CP2K builds with CUDA (via makefile), ACCFLAGS must have -Xcompiler='-fopenmp' added

See https://github.com/cp2k/dbcsr/issues/264#issuecomment-606465049

**Comment by alazzaro** [comment]
@hfp Thanks for pointing out this problem!
Actually, I see the toolchain does the proper setting of the flags, but the standard arch files do not.

I like your idea of adding automatically the Xcompiler, i.e.

```
NVFLAGS += $(addprefix -Xcompiler $(NULL),$(filter-out -Wl%,$(OPTFLAGS)))
```

Since the standard arch file doesn't have the OPTFLAGS variable, I would suggest using the CXXFLAGS instead. Therefore, I've added the following lines to the .cp2k/Makefile

```
> git diff
diff --git a/.cp2k/Makefile b/.cp2k/Makefile
index 20d4f16..c66ba0b 100644
--- a/.cp2k/Makefile
+++ b/.cp2k/Makefile
@@ -138,6 +138,9 @@ CXXFLAGS += -D__CUDA
 ifeq (,$(findstring -arch,$(ACCFLAGS)))
 override ACCFLAGS += -arch sm_$(ARCH_NUMBER)
 endif
+ifeq (,$(findstring -Xcompiler,$(ACCFLAGS)))
+override ACCFLAGS += -Xcompiler="$(CXXFLAGS)"
+endif
 # If compiling with hipcc
 else ifneq (,$(findstring hipcc,$(ACC)))
 override ACCFLAGS += -D__HIP
```

Is this OK?

Of course, I need to update the [INSTALL.md](https://github.com/cp2k/cp2k/blob/master/INSTALL.md#2j-cuda-optional-improved-performance-on-gpu-systems) in CP2K to make sure people they declare a propose CXXFLAGS...

**Comment by hfp** [comment]
Looks good to me. Sorry, yes the `OPTFLAGS` are outgrown; `CXXFLAGS` are the right thing. I like that your implementation just attempts to sanitize for the case something is missing.
