### ISSUE TITLE
Remove unused arrays for clusters

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#34]

**Comment by hfp** [comment]
Is there an interest to get a CP2K PR to accomodate this change?

**Comment by alazzaro** [comment]
No, it was already not used in CP2K.

**Comment by hfp** [comment]
At least I need some code changes: https://github.com/cp2k/cp2k/pull/330

**Comment by alazzaro** [comment]
Oh yes, v2 will require several changes in CP2K...

**Comment by dithillobothrium** [comment]
Is cp2k also fixed? Because it does not compile without clusters?

**Comment by hfp** [comment]
https://github.com/cp2k/cp2k/pull/330#issuecomment-487904329

Perhaps a starting point but there is more work needed.
