### ISSUE TITLE
introduce clang-format

### ISSUE THREAD

**Issue by hfp** [cp2k/dbcsr#359]
Introduce `clang-format` and reformat files when committed. Please also refer to #358, which mentions the infrastructure to reformat during commit and also the PROS and CONS of a customized code-format (`.clang-format`).

**Comment by hfp** [comment]
Quick command to concatenate all C/C++ code:

```bash
git ls-files *.c* *.h* | grep -v "..*\.cmake" \
    | grep -v "\.ci" | grep -v "\.cp2k" | grep -v tools | grep -v ..*\.yml \
    | xargs -I {} cat {} >> format.c
```

To reformat the concatenated code from above:

```bash
clang-format --style=LLVM format.c > format-llvm.c
clang-format --style=file format.c > format-custom.c
```

The custom format is located [here](https://github.com/hfp/libxsmm/blob/master/.clang-format).

It is hard to judge whether one is better than the other (especially since all code is concatenated), however some level of customization might be advisable since the LLVM-style for instance reformats comment-blocks, which affects the current copyright header (well, one could adjust the copyright header...)

**Comment by hfp** [comment]
I had to change the file extension to something other than `.c`.

[format.txt](https://github.com/cp2k/dbcsr/files/4947787/format.txt)
[format-llvm.txt](https://github.com/cp2k/dbcsr/files/4947789/format-llvm.txt)
[format-custom.txt](https://github.com/cp2k/dbcsr/files/4947788/format-custom.txt)

**Comment by oschuett** [comment]
Thanks for the comparison. I'm starting to see your point. While we could certainly change the copyright banner, the reflow of comments is annoying and would require manual rework. And I must admit that having more than 80 chars per line is also very nice.

**Comment by dev-zero** [comment]
since you also updated the cmake, we could also incorporate `cmake-format`.

**Comment by alazzaro** [comment]
clang-format was introduced with a workaround for the FYPP processings.
