### ISSUE TITLE
Wrong results with dbcsr_scale_by_vector with scale="left"

### ISSUE THREAD

**Issue by ambmax00** [cp2k/dbcsr#362]
When using `dbcsr_scale_by_vector`, with side="left", blocks with different row/col sizes are not scaled correctly. This is likely due to the line
https://github.com/cp2k/dbcsr/blob/396964ca58f55d56212c72b8be657561e0c44e9a/src/ops/dbcsr_operations.F#L564
and subsequent lines, which instead should be
```
DO irow = i, i + a_col_size*a_row_size - 1, a_row_size
```
and then it gives the correct results in my case.

**Comment by dev-zero** [comment]
ugh, that's an ugly one. We definitely have to improve our tests :(
