### ISSUE TITLE
make failed with gfortran 10.2.0

### ISSUE THREAD

**Issue by Jim-215-Fisher** [cp2k/dbcsr#377]
System: gfortran 10.2.0
Error "2" referred to at block(1:nze) and error "1" referred at block(1)

[ 14%] Building Fortran object src/CMakeFiles/dbcsr.dir/utils/dbcsr_string_utilities.F.o
[ 16%] Building Fortran object src/CMakeFiles/dbcsr.dir/work/dbcsr_work_operations.F.o
[ 16%] Building Fortran object src/CMakeFiles/dbcsr.dir/block/dbcsr_block_access.F.o
/home/mpiuser/buildpkg/cp2k/dbcsr-2.0.1/_build/src/block/dbcsr_block_access.F:2521:61:

 2448 |                  CALL caxpy(nze, scale, block(1:nze), 1, &
      |                                                             2                     
......
 2521 |                     CALL caxpy(nze, CMPLX(1.0, 0.0, real_4), block(1), 1, &
      |                                                                                               1
Error: Element of assumed-shape or pointer array as actual argument at (1) cannot correspond to actual argument at (2)
/home/mpiuser/buildpkg/cp2k/dbcsr-2.0.1/_build/src/block/dbcsr_block_access.F:2048:61:

 1975 |                  CALL zaxpy(nze, scale, block(1:nze), 1, &
      |                                                                      2                     
......
 2048 |                     CALL zaxpy(nze, CMPLX(1.0, 0.0, real_8), block(1), 1, &
      |                                                                                                      1
Error: Element of assumed-shape or pointer array as actual argument at (1) cannot correspond to actual argument at (2)
/home/mpiuser/buildpkg/cp2k/dbcsr-2.0.1/_build/src/block/dbcsr_block_access.F:1575:48:

 1502 |                  CALL saxpy(nze, scale, block(1:nze), 1, &
      |                                                                      2        
......
 1575 |                     CALL saxpy(nze, 1.0_real_4, block(1), 1, &
      |                                                                               1
Error: Element of assumed-shape or pointer array as actual argument at (1) cannot correspond to actual argument at (2)
/home/mpiuser/buildpkg/cp2k/dbcsr-2.0.1/_build/src/block/dbcsr_block_access.F:1102:48:

 1029 |                  CALL daxpy(nze, scale, block(1:nze), 1, &
      |                                                                      2        
......
 1102 |                     CALL daxpy(nze, 1.0_real_8, block(1), 1, &
      |                                                                                  1
Error: Element of assumed-shape or pointer array as actual argument at (1) cannot correspond to actual argument at (2)
make[2]: *** [src/CMakeFiles/dbcsr.dir/build.make:635: src/CMakeFiles/dbcsr.dir/block/dbcsr_block_access.F.o] Error 1

**Comment by mbanck** [comment]
That's blocking cp2k in Debian/Ubuntu now

**Comment by dev-zero** [comment]
@Jim-215-Fisher which version of DBCSR is this? I belive we fixed all of the occurrences in 58ee9709545deda8524cab804bf1f88a61a864ac

**Comment by dev-zero** [comment]
Ok, I can not reproduce this with latest `develop` and gcc-10.2. Hence this will be fixed in the next 2.1 release.
