### ISSUE TITLE
CP2K error, seems due to DBCSR-GPU

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#379]
See https://github.com/cp2k/cp2k/issues/893

**Comment by alazzaro** [comment]
@oschuett could you attach the simplified input file you use to understand the problem?

**Comment by oschuett** [comment]
Sure, [here](https://github.com/cp2k/cp2k/files/5602113/hf_omp_short.inp.gz) it is. To narrow this down I added a bunch of `WRITE (*,*) dbcsr_checksum(foo)` and used `diff -y` to compare outputs with one and two OpenMP threads.

**Comment by alazzaro** [comment]
So, update on the issue:
1. The bug is there since a while (probably since the beginning of the thread distribution part, see below)
2. it is not related at all to the GPU execution. The point is that the CPU execution does densification, while the GPU doesn't. It turns out (as @oschuett pointed out) that the densification is able to fix the problem. If we remove the densification for the CPU, then the problem will show up there too...
3. I turns out that the problem is in the [thread distribution](https://github.com/cp2k/dbcsr/blob/05e93bd4f9aab65862b769c2c8388667a2a845cc/src/dist/dbcsr_dist_methods.F#L454). This particular benchmark has several block sizes, so the thread distribution is "highly" optimized. For the dense case, the thread distribution is re-evaluated as result of the densification, that's why we don't see the problem there. The scary thing is that we can say that in principle all GPUs/dense runs were buggy...
4. It seems that the problem is that the C thread distribution is different by the A thread distribution. Investigating more...
