### ISSUE TITLE
Add a check in the makefile to verify is fypp is installed

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#38]
This check is required when people download DBCSR as a zip file and they don't get fypp included (since it is a submodule). In this case, a message like:
Fypp is not installed in the default position ..., please install it and use make FYPPEXE=<> ... to point to it.

**Comment by dev-zero** [comment]
Is this still an issue? With the automated release tarball generation via Travis CI, all future release tarballs will contain Fypp as required.
Futhermore I don't see how we can do that reliably: if `.git` is missing, the only thing we get from `.gitmodules` is the branch for Fypp. Even though Fypp doesn't change much, we could in principal end-up with a different version of Fypp than we've tested with if we just fetch Fypp.

Therefore the only things we can reliably do, are:

* if `.git.` is present but Fypp is not, do a `git submodule update --init`
* if neither `.git` nor Fypp are present, terminate the build and inform the user to obtain DBCSR properly as described in `README.md`
