### ISSUE TITLE
Bug when cublas and cusmm are used at the same time

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#389]
See https://github.com/cp2k/cp2k/issues/911

**Comment by alazzaro** [comment]
@oschuett 
For the discussion we had on this bug, I'm not completely sure that your change will make the difference here... Well, probably I'm fully clear how the stream GPU mechanism works in DBCSR...

In the current code used by DBCSR in CP2K, each CPU thread submits to the GPU on a different portion of the C matrix. Then, each thread is attached to a stream (via a round-robin). Now, I understand the cusmm uses atomics, indeed we run simultaneous GPU threads that can operate within a CPU thread, so we need to be thread-safe. That's OK.
Assuming that at some point we get a large kernel, this is submitted by each CPU thread (so independent C-portions) via a cublas call in a loop of calls within the same stream. The code is what you linked:

https://github.com/cp2k/dbcsr/blob/d2dfe6e25efde255f72ac27f542124b69c7af1c2/src/mm/dbcsr_acc_operations.F#L150

Yes, the cublas DGEMM is not thread-safe, but we are running only a cublas dgemm at the time (they serialize within the same stream)... This is not a batched call, where for sure we will have problems.

Even assuming previous cusmm calls competing with the cublas calls, they still run on the same stream and serialize...

Should I assume that the consecutive calls on the same stream somehow are not serialized?
Could you elaborate where we have symultanous cublas dgemm calls accessing to the same C data?

**Comment by oschuett** [comment]
Each OpenMP threads has multiple stack buffers (for different combinations of mnk). Each stack buffer has it's own stream (more or less). Hence, there are multiple streams per OpenMP thread.

Unfortunately, this stream / even part is quite complex. Have a look at Figure 4 in the [book chapter](https://www.cp2k.org/_media/gpu_book_chapter_submitted.pdf).

**Comment by alazzaro** [comment]
Thanks @oschuett , now I understand the stacks and streams relation...
Now, your idea of using the global stream per each thread, i.e. `c_area%memory_type%acc_stream`, will make cublas calls OK. So we have
* cusmm calls OK
* cublas calls OK
What about the mix case, i.e. cublas and cusmm operating on the same C-block?

**Comment by oschuett** [comment]
Work on the `c_area%memory_type%acc_stream` can not overlap with previous cusmm kernels because of [this](https://github.com/cp2k/dbcsr/blob/d2dfe6e25efde255f72ac27f542124b69c7af1c2/src/mm/dbcsr_mm_accdrv.F#L587). 

Future kernels can not overlap either as long as you continue to call [acc_stream_synchronize](https://github.com/cp2k/dbcsr/blob/d2dfe6e25efde255f72ac27f542124b69c7af1c2/src/mm/dbcsr_acc_operations.F#L190).

If you want to start submitting the cublas kernels asynchronously, then you could make future cusmm kernels [wait](https://github.com/cp2k/dbcsr/blob/d2dfe6e25efde255f72ac27f542124b69c7af1c2/src/mm/dbcsr_mm_accdrv.F#L564) by updating the `c_area%acc_ready` event.

**Comment by alazzaro** [comment]
OK, let me come up with a first patch and then we discuss...

**Comment by alazzaro** [comment]
@oschuett I need your advice on the PR for fixing this bug.

I think I have to add a
```
CALL acc_stream_wait_event(c_area%memory_type%acc_stream, stackbuf%ready)
```
just after this line:

https://github.com/cp2k/dbcsr/blob/8e76ca107a595916811d0260f7956d3f32f5c33d/src/mm/dbcsr_mm_accdrv.F#L568

Do you confirm?

**Comment by oschuett** [comment]
@alazzaro, I think this call to `acc_stream_wait_event` is not needed, because `libsmm_acc_process_blas` uses `param_stack_host`. Hence, it does not have to wait for the stack buffer to be uploaded to the device.

**Comment by alazzaro** [comment]
The point is that if I don't add it, the code simply gets wrong results... See here:

https://object.cscs.ch/v1/AUTH_40b5d92b316940098ceb15cf46fb815e/dbcsr-artifacts/logs/build-609/

I went to debug it and found that solution, but I want to ask you since you know the GPU part better than anyone else...
