### ISSUE TITLE
C tensor interface error after rebase: "This should not happen"

### ISSUE THREAD

**Issue by ambmax00** [cp2k/dbcsr#435]
Getting ready to finish up the pull request #348 for the c matrix API, I have merged upstream into my branch. Before, the base was at commit 5499849d5ba9af39b2a3af8f0f3ce3814f5eebe2. I have not changed any significant part of the c tensor interface.

However, when I try to test my program, it fails for tensor contractions with the form 
`(ab|c) x (ab|ef) = (ef|c)` 
All other types work. Note that remapping the 4-dimensional tensor makes it work: 
`(ab|c) x (abe|f) = (ef|c)`

Here's the extended output for one such contraction:
````
Iteration Nr      Energy (Ht)       Error (Ht)        RMS alpha(Ht)     RMS beta(Ht)      
--------------------------------------------------------------------------------
Forming Fock matrix...
--------------------------------------------------------------------------------
DBCSR TENSOR CONTRACTION: p dummy x ATOM_rank0_8_eri_batched_work = J_bbd
--------------------------------------------------------------------------------
 GLOBAL INFO OF p dummy
   block dimensions:      1     1     1
   full dimensions:       14      14       1
   process grid dimensions:      1     1     1
   Block sizes:
       Dim 1: 14 
       Dim 2: 14 
       Dim 3:  1 
   Block distribution:
       Dim 1:   0 
       Dim 2:   0 
       Dim 3:   0 
 DISTRIBUTION OF p dummy
              Number of non-zero blocks:                                       1
              Percentage of non-zero blocks:                              100.00
              Average number of blocks per CPU:                                1
              Maximum number of blocks per CPU:                                1
              Average number of matrix elements per CPU:                     196
              Maximum number of matrix elements per CPU:                     196
 GLOBAL INFO OF ATOM_rank0_8_eri_batched_work
   block dimensions:      1     1     1     1
   full dimensions:       14      14      14      14
   process grid dimensions:      1     1     1     1
   Block sizes:
       Dim 1: 14 
       Dim 2: 14 
       Dim 3: 14 
       Dim 4: 14 
   Block distribution:
       Dim 1:   0 
       Dim 2:   0 
       Dim 3:   0 
       Dim 4:   0 
 DISTRIBUTION OF ATOM_rank0_8_eri_batched_work
              Number of non-zero blocks:                                       1
              Percentage of non-zero blocks:                              100.00
              Average number of blocks per CPU:                                1
              Maximum number of blocks per CPU:                                1
              Average number of matrix elements per CPU:                   38416
              Maximum number of matrix elements per CPU:                   38416
 INDEX INFO
              tensor index: (bca) x (debc) = (dea)
              matrix index: (bc|a) x (de|bc) = (de|a)
 aligning tensor index with data
 INDEX INFO
              tensor index: (bca) x (debc) = (dea)
              matrix index: (bc|a) x (de|bc) = (de|a)
 large tensors: 1, 3; small tensor: 2
 sorting contraction indices
 compatibility of p dummy: Transposed
 compatibility of J_bbd: Transposed
 No redistribution of p dummy
 No redistribution of J_bbd
 compatibility of ATOM_rank0_8_eri_batched_work: Transposed
 No redistribution of ATOM_rank0_8_eri_batched_work
 INDEX INFO
              tensor index: (bca) x (debc) = (dea)
              matrix index: (bc|a) x (de|bc) = (de|a)
--------------------------------------------------------------------------------
DBCSR TAS MATRIX MULTIPLICATION: p dummy matrix x ATOM_rank0_8_eri_batched_work matrix = J_bbd matrix
--------------------------------------------------------------------------------
 mm dims:            1            1            1

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                            should not happen                         *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                     dbcsr_tas_mm.F:1154 *
 *******************************************************************************


 ===== Routine Calling Stack ===== 

            8 reshape_mm_compatible
            7 dbcsr_tas_total
            6 dbcsr_tas_multiply
            5 dbcsr_tas_result_index
            4 dbcsr_tas_total
            3 dbcsr_tas_multiply
            2 dbcsr_t_contract
            1 dbcsr_t_total
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
````
This is compiler-independent, and does not depend on the number of threads or processes used.
Running gdb, it actually fails at https://github.com/cp2k/dbcsr/blob/acf88120a24330a7447eead1eeb15fd80693404d/src/tas/dbcsr_tas_mm.F#L1095

and inside that function at
https://github.com/cp2k/dbcsr/blob/acf88120a24330a7447eead1eeb15fd80693404d/src/tas/dbcsr_tas_mm.F#L1150-L1156

split_rowcol is equal to 2 and split_rc is equal to 1.

Valgrind does not give any invalid reads or writes.

That's as far as I got, I don't really know how to proceed, any insight is appreciated.

**Comment by alazzaro** [comment]
So, I'm a bit confused: is this something which was introduced after https://github.com/cp2k/dbcsr/commit/5499849d5ba9af39b2a3af8f0f3ce3814f5eebe2 ?

**Comment by ambmax00** [comment]
Yes, after rebasing my branch from 5499849 to acf88120a24330a7447eead1eeb15fd80693404d, the error started occurring.

**Comment by alazzaro** [comment]
OK, that one is a pretty old commit...
Can you try with a recent one? I see @pseewald did some changes in the TAS part, probably we are lucky to find which commit introduced the problem...

**Comment by ambmax00** [comment]
Ok, I will go through each commit which modifies tensor or tas, and see where it stops working...

**Comment by alazzaro** [comment]
Thanks! Well, you can go for chunks of commits... What I mean is that after each major changes in TAS, Patrick did a release...

**Comment by ambmax00** [comment]
It stops working at commit 7e491345fa5e1f2648eacd4f7b7f2885d746907a
This is the commit where the error message was actually introduced...

**Comment by alazzaro** [comment]
OK, then this is a question for @pseewald ...
From what I can recall, Patrick introduced some more restricts splitting of the matrices, so maybe it is something we have to change from the design point of view...

**Comment by pseewald** [comment]
Sorry for not responding, and thanks for the detailed information. I‘ll try to fix this within the coming week.

**Comment by hfp** [comment]
Since this issue is present in DBCSR v2.1.0, I wonder if the tensors are already used in CP2K? If so, upcoming CP2K v8.2 is affected. Stretch time for v8.2 is mid of May, but fixes would need to take place asap. for proper testing...

**Comment by ambmax00** [comment]
Hi, any update on this issue?

**Comment by alazzaro** [comment]
@pseewald Do you have time to look in this issue?

**Comment by ambmax00** [comment]
For now, replacing `DBCSR_ABORT("should not happen") ` by `nsplit_prv = 1` seems to resolve the issue for me in all cases, though I don't know if it leads to bugs somewhere else. I will look into it.

**Comment by alazzaro** [comment]
@ambmax00 could you make the change in any case? we can test as part of the standard CP2K procedure...
