### ISSUE TITLE
FC default in Makefile overrides environment variables in cp2k builds

### ISSUE THREAD

**Issue by ltalirz** [cp2k/dbcsr#441]
**Describe the bug**
The DBCSR Makefile ~13 months ago [introduced defaults](https://github.com/cp2k/dbcsr/blame/master/.cp2k/Makefile) for variables like `FC`, e.g. `FC        = mpif90`.
As cp2k includes this makefile, this results in the value of corresponding environment variables (e.g. `FC`) being ignored, if they are not specified explicitly in the arch-file.

We noticed this on conda-forge, where the serial cp2k builds suddenly started looking for `mpif90` after upgrading from v7.1 to v8.1 https://github.com/conda-forge/cp2k-feedstock/pull/23#issuecomment-819323100

@dev-zero suggests to either replace the defaults by `?=` (see [here](https://www.gnu.org/software/make/manual/html_node/Setting.html) for meaning) or to remove them.

**Comment by hfp** [comment]
The `?=` might be a good option. Though, DBCSR's hidden Makefile as included by CP2K is (was?) also meant to enable standalone builds of DBCSR (at least that is what is still possible/working).

**Comment by oschuett** [comment]
I think, we should just move ahead with our plan to build DBCSR via the toolchain using cmake.

**Comment by alazzaro** [comment]
To clarify some points:

> As cp2k includes this makefile, this results in the value of corresponding environment variables (e.g. FC) being ignored, if they are not specified explicitly in the arch-file.

It is the other way around, DBCSR makefile includes the arch file (we don't include the CP2K makefile). 
This is done via:

https://github.com/cp2k/dbcsr/blob/046f9db8d4aedf81ea3d7a998bc7cc413a92d468/.cp2k/Makefile#L95-L97

Now, that include is after the default `CXX`,`CC`, `FC`... so the assumption is that the CP2K arch file must provide those entries. Same for all other flags, `FCFLAGS`, `CXXFLAGS`,... So, a simple replacement with `?=` is not enough, we need to change the order of the inclusion. 

So, now we want to consider the case where those variables are not declared in the CP2K arch file. If so, I suggest removing the default session in DBCSR. Indeed, we can have mixed situations, where some variable take defaults, some other comes from the arch file... As Ole said, the Makefile will disappear at some point...

**Comment by alazzaro** [comment]
This problem has been fixed in the commit https://github.com/cp2k/dbcsr/commit/7cc33c52ef14fce0a82766aea2f88b1dc432a73d
