### ISSUE TITLE
CMake: option to switch SMM-implementation missing

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#46]
maybe something like a tri-state?

* `WITH_SMM=blas`
* `WITH_SMM=libxsmm`
* `WITH_SMM=libsmm`

**Comment by dev-zero** [comment]
will wait for the libxsmm-1.10 release featuring a pkg-config file to implement the libxsmm-check hfp/libxsmm#269 then the following should be enough to properly detect `libxsmm` and get the required flags:

```libxsmm
find_package(PkgConfig REQUIRED)

if (WITH_SMM STREQUAL "libxsmm")
  pkg_check_modules(LIBXSMM REQUIRED libxsmm)
elseif (WITH_SMM STREQUAL "libsmm")
  ...
elseif (WITH_SMM STREQUAL "libsmm")

endif ()

[...]

target_link_libraries(dbcsr PUBLIC ${LIBXSMM_LIBRARIES})
target_compile_options(dbcsr PUBLIC ${LIBXSMM_CFLAGS_OTHER})
```

@alazzaro do we want a quad-state `WITH_SMM=auto` (default), `WITH_SMM=blas`, `WITH_SMM=libxsmm`, `WITH_SMM=libsmm` with `auto` trying to discover and use libxsmm, libsmm automatically if found or should we just use `blas` as the default and only do detection if the user specifies `-DWITH_SMM=lib(x)smm`?

**Comment by alazzaro** [comment]
I would prefer the latter solution. In principle, libsmm is not suggested (unless they are using no-x86 platform), while I must admit in most cases MKL is already doing a good job (therefore libxsmm is not needed)... We will make clear this point in the documentation...

**Comment by dev-zero** [comment]
good, the latter solution is also the easier one :+1:
