### ISSUE TITLE
Error: invalid preprocessing directive

### ISSUE THREAD

**Issue by Timstone813** [cp2k/dbcsr#469]
I successfully cmake dbcsr using the following code:
`/public/home/godeye2021/cmake/bin/cmake .. -DUSE_MPI=ON -DUSE_HIP=ON -DUSE_SMM=blas  -DUSE_OPENMP=OFF -DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_CXX_COMPILER=hipcc -DUSE_OPENMP=OFF -DUSE_SMM=libxsmm -DUSE_ACCEL=hip -DWITH_CUDA_PROFILING=OFF -DWITH_C_API=ON -DWITH_EXAMPLES=ON -DWITH_GPU=Mi50 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DTEST_MPI_RANKS=1 -DTEST_OMP_THREADS=1 -DCMAKE_INSTALL_PREFIX=~/cp2k-hip_backend/exts/dbcsr-install`

But when I make. The following error occurred!

`Printing them to file parameters.h 
[  1%] Built target parameters 
Scanning dependencies of target dbcsr 
[  2%] Building Fortran object src/CMakeFiles/dbcsr.dir/acc/dbcsr_acc_devmem.F.o 
/public/home/godeye2021/cp2k-hip_backend/exts/dbcsr/build/src/acc/dbcsr_acc_devmem.F:490:0:   
#:set instances = [ ('i4', 'int_4_size',    'INTEGER(kind=int_4)'), &   
Error: invalid preprocessing directive #: 
/public/home/godeye2021/cp2k-hip_backend/exts/dbcsr/build/src/acc/dbcsr_acc_devmem.F:497:0:   
#:for nametype, size, type in instances   
Error: invalid preprocessing directive #: 
/public/home/godeye2021/cp2k-hip_backend/exts/dbcsr/build/src/acc/dbcsr_acc_devmem.F:550:0:   
#:endfor   
Error: invalid preprocessing directive #: 
/public/home/godeye2021/cp2k-hip_backend/exts/dbcsr/build/src/acc/dbcsr_acc_devmem.F:491:20:   
                    ('i8', 'int_8_size',    'INTEGER(kind=int_8)'), &                     1 
Error: Unclassifiable statement at (1) 
/public/home/godeye2021/cp2k-hip_backend/exts/dbcsr/build/src/acc/dbcsr_acc_devmem.F:499:23:      
SUBROUTINE host2dev_${nametype}$_1D(this, hostmem, stream)                        1 
Fatal Error: Invalid character ‘$’ at (1). Use ‘-fdollar-ok’ to allow it as an extension 
compilation terminated. 
make[2]: *** [src/CMakeFiles/dbcsr.dir/build.make:505: src/CMakeFiles/dbcsr.dir/acc/dbcsr_acc_devmem.F.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:1193: src/CMakeFiles/dbcsr.dir/all] Error 2 
make: *** [Makefile:160: all] Error 2`

**Comment by hfp** [comment]
Is this the `develop` branch? Also, have you cloned the repository and then updated/initialized the submodules?

**Comment by Timstone813** [comment]
I have tried various versions ,
Add HIP Profiling support (#461) …    commit
52a3d0cfc6a7bb6440a2661b5893587b868451cb
Add Mi100 support (#452)   commit 9792a8021f390834153a95ded4d9bdcbf998c611
dbcsr-develop
All the same error. These are my submodules:
[image: image.png]

Hans Pabst ***@***.***> 于2021年6月28日周一 下午3:22写道：

**Comment by dev-zero** [comment]
@Timstone813 can you check whether a simple configuration (`cmake .. && make -j`) works?
And please post the output of make when running with `make VERBOSE=1` so we see the actual command. 
Also I don't think that specifying the HIP compiler in such a way is necessary or correct. @gsitaram ?

**Comment by Timstone813** [comment]
I tried the develop version, it's still the same.
[image: Snipaste_2021-06-28_21-07-15.png]
[image: Snipaste_2021-06-28_21-08-06.png]
[image: Snipaste_2021-06-28_21-08-26.png]
[image: Snipaste_2021-06-28_21-08-41.png]
[image: Snipaste_2021-06-28_21-08-56.png]
[image: Snipaste_2021-06-28_21-10-36.png]
[image: Snipaste_2021-06-28_21-10-46.png]

Tiziano Müller ***@***.***> 于2021年6月28日周一 下午8:13写道：

**Comment by dev-zero** [comment]
@Timstone813 please use the github webinterface to upload images, they are not visible...

**Comment by Timstone813** [comment]
Thanks for reminding.
cmake succeeded 
make error 
![Snipaste_2021-06-28_21-07-15](https://user-images.githubusercontent.com/21101211/123643933-7e70ad00-d857-11eb-844c-3b1420df56f2.png)
![Snipaste_2021-06-28_21-08-06](https://user-images.githubusercontent.com/21101211/123644004-8fb9b980-d857-11eb-971f-dc5404f7fa81.png)
![Snipaste_2021-06-28_21-08-26](https://user-images.githubusercontent.com/21101211/123644020-947e6d80-d857-11eb-98a8-acb6186e45d1.png)
![Snipaste_2021-06-28_21-08-41](https://user-images.githubusercontent.com/21101211/123644034-97795e00-d857-11eb-8b75-63eb24efe4dc.png)
![Snipaste_2021-06-28_21-08-56](https://user-images.githubusercontent.com/21101211/123644062-9c3e1200-d857-11eb-9607-000e74f72e6d.png)
![Snipaste_2021-06-28_21-10-36](https://user-images.githubusercontent.com/21101211/123644079-a06a2f80-d857-11eb-89f1-dd055715c55f.png)
![Snipaste_2021-06-28_21-10-46](https://user-images.githubusercontent.com/21101211/123644116-a7913d80-d857-11eb-9891-a75204fed7b7.png)

**Comment by dev-zero** [comment]
@Timstone813 it seems that for some reason the fypp preprocessor didn't run properly. Can you please try with a clean build directory and with a really simple configuration? See my previous message.

**Comment by hfp** [comment]
@Timstone813 @dev-zero This was my reason to ask for whether submodules have been cloned/initialized or not. Unfortunately, I was not able to view the attached image mentioned in the [comment](https://github.com/cp2k/dbcsr/issues/469#issuecomment-869615958).

**Comment by Timstone813** [comment]
> @Timstone813 it seems that for some reason the fypp preprocessor didn't run properly. Can you please try with a clean build directory and with a really simple configuration? See my previous message.

My fypp version is V3.1. Is it too high?
I have successfully made the version: commit 9bd2dc31a0527
