### ISSUE TITLE
[cmake] introduce blacklist facilities

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#54]
we know that certain OpenMPI, compiler or BLAS/LAPACK versions are broken

to reduce the workload it might be beneficial to maintain a list of broken deps in CMake

**Comment by alazzaro** [comment]
Partially done for OpenMPI, see #307

**Comment by dev-zero** [comment]
This issue was meant as a meta-issue for implementing the general facility in CMake, which we did: we have examples for both OpenMPI and Compilers. If we have other checks which should be added, let's make them actual issues we can work!
