### ISSUE TITLE
Add CP2K support for A100

### ISSUE THREAD

**Issue by shahzebsiddiqui** [cp2k/dbcsr#553]
I am trying to build CP2K for our NVIDIA A100 system using spack, I reported an issue and according to @dev-zero in https://github.com/spack/spack/issues/28554#issuecomment-1033840686 he suggested we post an issue here so support can be added.

**Comment by alazzaro** [comment]
Autotuning the kernels for A100 is definitely on our schedule. In the meantine, you can use V100 kernels.

**Comment by dev-zero** [comment]
done in #629
