### ISSUE TITLE
Compilation problem when using intel ifort

### ISSUE THREAD

**Issue by Quark195** [cp2k/dbcsr#586]
Dear developers,
I ran into a problem compiling the library dbcsr for CP2K.
For compilation, I use the intel ifort version 19.1.0.139 compiler. Cmake  version 3.22.3. (Ubuntu 21.10). 
For installation, I used the latest version of dbcsr-2.2.0

`CC=mpiicc FC=mpiifort CXX=mpicxx cmake -DBLA_VENDOR=Intel10_64lp_seq ..`

After which I am getting an error.

`(base) quark@quark-desktop:~/dbcsr_3/dbcsr-2.2.0/build$ source /home/quark/intel/compilers_and_libraries_2020.0.139/linux/bin/compilervars.sh intel64
(base) quark@quark-desktop:~/dbcsr_3/dbcsr-2.2.0/build$ CC=mpiicc FC=mpiifort CXX=mpicxx cmake -DBLA_VENDOR=Intel10_64lp_seq ..-- Using BLAS for Small Matrix Multiplication
-- A library with LAPACK API found.
CMake Error at cmake/fypp-sources.cmake:9 (message):
  Failed to find the FYPP preprocessor.
Call Stack (most recent call first):
  src/CMakeLists.txt:3 (include)
-- Configuring incomplete, errors occurred!
See also "/home/quark/dbcsr_3/dbcsr-2.2.0/build/CMakeFiles/CMakeOutput.log".`

Please tell me how to fix the error.

Best regards, Eugene

[CMakeOutput.log](https://github.com/cp2k/dbcsr/files/8308071/CMakeOutput.log)

**Comment by alazzaro** [comment]
How are you downloading the library?
The error message says that FYPP is missing, so I assume you are using the wrong tar file that doesn't include FYPP as submodule. Please use https://github.com/cp2k/dbcsr/releases/download/v2.2.0/dbcsr-2.2.0.tar.gz

**Comment by Quark195** [comment]
I have the install I downloaded from [https://github.com/cp2k/dbcsr/releases/tag/v2.2.0]
Your version has been successfully installed. Thank you very much.
Best regards, Eugene
