### ISSUE TITLE
GitHub Actions fail to checkout repository

### ISSUE THREAD

**Issue by hfp** [cp2k/dbcsr#607]
Perhaps it can be worked around with suggestions taken from https://github.com/actions/checkout/issues/760. However, it is not understood well why this issue appeared.

**Comment by alazzaro** [comment]
yes, it seems so... 
I discussed with @dev-zero . Ideally, it would be good to have an official fix, no workaround...

let's rely on daint for the moment...

**Comment by hfp** [comment]
ACK, i.e., if Daint-CI passes - PR can be merged.

**Comment by hfp** [comment]
Btw, rerunning failed actions does not help.

**Comment by dev-zero** [comment]
that's a fallout of a fix to the latest git CVE (and the git versions inside most of our build containers have been updated), I expect a general solution in the actions/checkout to appear soon'ish.

**Comment by hfp** [comment]
The issue is supposedly fixed (and already released upstream). I reran all failed tests for the (currently) [latest merged commit](https://github.com/cp2k/dbcsr/commit/6a852ebe87838d033abbc30e2827e83409a5ec7e) (which passed at least Daint-CI for the merge), and everything seems to pass now except the test called "[pre-commit](https://github.com/cp2k/dbcsr/runs/6049090067)" which is still failing:

```text
fatal: unsafe repository ('/__w/dbcsr/dbcsr' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/dbcsr/dbcsr
```

This might be also because of simply rerunning tests for something committed before the fix.

**Comment by hfp** [comment]
The `pre-commit` check continues to fail even for new PRs.

**Comment by alazzaro** [comment]
I think the problem is the that here we are running the command:

```
pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
```

which includes `git`.  I think we can add `git config --global --add safe.directory` for this stage. @dev-zero any idea?

**Comment by dev-zero** [comment]
@alazzaro yes, this seems to be [the solution for now](https://github.com/actions/checkout/issues/766). Applied to both our pre-commit and as a step to the github pages deployment which [suffers from the same issue](https://github.com/JamesIves/github-pages-deploy-action/issues/1083).
