### ISSUE TITLE
'dbcsr_trace_ab' is only correct for a symmetric matrix 'b'

### ISSUE THREAD

**Issue by jkn93** [cp2k/dbcsr#68]
This is a rather minor issue, since qc-developers will usually use this with real symmetric matrices,
e.g., Tr[PF] or Tr[PS], which will work just fine. To be formally correct, one could either rename this
function to 'dot_ab' or actually transpose matrix b.

**Comment by dev-zero** [comment]
@alazzaro do we want to fix this prior to the final 1.0.0 release?

**Comment by alazzaro** [comment]
No, let's leave it for the v2.0 (it is a change in the API w.r.t. the current DBCSR in CP2K)

**Comment by alazzaro** [comment]
@jkn93 We are going to handle this issue. Could you elaborate a bit more on what you want to change?

**Comment by jkn93** [comment]
Formally, one would have to transpose matrix B to obtain the trace from the dot-product:
Tr[AxB] = sum_i (A x B)_ii = sum_ij (A_ij * B_ji) = dot(A,B^T).
As I said, the old routine is ok as long as B is real and symmetric.

**Comment by jkn93** [comment]
@alazzaro ...or A is real/symmetric

**Comment by alazzaro** [comment]
OK, thanks for the explanation. I think there was a misunderstanding in my previous request, I was referring to which change to do in the code. The theory is clear, the DBCSR function name "trace" is wrong, actually we evaluate the dot(A,B) != Tr[AxB] in general, as you explained.
So, I agree to rename the function to dbcsr_dot would be a better option. Is that OK?

**Comment by jkn93** [comment]
Fine for me...

**Comment by hfp** [comment]
I can send a PR for CP2K to accomodate the changes. Let me know what the timeline is for DBCSRv2 in CP2K.

**Comment by alazzaro** [comment]
I think @dithillobothrium is already working on it as a consequence of PR #181 .
Reasonable we will merge that PR in a ~1 week and finalize the v2.0 just after. Let's wait for that.

**Comment by hfp** [comment]
Thank you!
