### ISSUE TITLE
Thread number has changed error if OMP_DYNAMIC=TRUE

### ISSUE THREAD

**Issue by hfp** [cp2k/dbcsr#705]
```txt
 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                        Thread number has changed                     *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                dbcsr_dist_methods.F:509 *
 *******************************************************************************
```

This issue is almost artificial and may be closed. However, the observation is about code at `dbcsr_dist_methods.F:509` being incompatible with a valid OpenMP environment.

**Comment by alazzaro** [comment]
This is not supported, actually (by design of the library). See https://github.com/cp2k/dbcsr/issues/217 for a similar discussion...

**Comment by alazzaro** [comment]
We can probably relax the condition, but it will require a reimplementation of the entire threading part...

**Comment by hfp** [comment]
I do not want to keep this open as an issue. Perhaps we can invent a new GitHub label resembling issue like "nice to have", meanwhile I am labeling it "postpone".
