### ISSUE TITLE
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation

### ISSUE THREAD

**Issue by hfp** [cp2k/dbcsr#732]
CI-tests are failing for `build-and-test (MPI=ON, OPENMP=ON, SMM=blas, mpich)`. More specifically, https://github.com/cp2k/dbcsr/blob/develop/tests/dbcsr_test_multiply.F#L753 performs a division by zero. The test should be hardened against this issue (and perhaps gracefully fail if the denominator becomes zero), and further the actual issue shall be investigated (MPICH?).

**Comment by alazzaro** [comment]
So, I've investigated this problem.
It has started in November when the github runners machines have moved > 2 cores available (4). By default, the tests take the number of available cores, so before the change it was 2. We also use 2 threads by default, so at the end we used 1 rank in the tests. Our unitests can fail when > 1 ranks are involved (it depends by the distribution of the blocks), therefore we have never seen this problem before the November change, while we see it now with 2 ranks. 
Fixed via https://github.com/cp2k/dbcsr/commit/21971fd58c44d79724ba875e875b14db3b9751ef
