### ISSUE TITLE
Remove code related to parameter prediction

### ISSUE THREAD

**Issue by hfp** [cp2k/dbcsr#837]
My proposal is to remove all code related to prediction incl. the Jupyter notebook(s). This and future pre-commits like the Python linter rejects for instance `src/acc/libsmm_acc/notebooks/inspect_training_data.ipynb`. Without porting this code to new versions of their dependencies, the pre-commit remains red. An alternative is to exclude/green-list related failures. The real concern is the lack of testing for the prediction. Removing the code also fixes the [security warning](https://github.com/cp2k/dbcsr/security/dependabot).

_Originally posted by @hfp in https://github.com/cp2k/dbcsr/issues/836#issuecomment-2325685546_

**Comment by alazzaro** [comment]
crosslink to https://github.com/cp2k/dbcsr/issues/805
